### ISSUE TITLE
Replace Less with styled components

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#100]

**Comment by HugoGranstrom** [comment]
Work cultures where you're "heavily encouraged" to drink doesn't really sound that nice 🤔 there are other "team building" activities one could do instead. 

But the London job seems really interesting, especially as it reflects your expertise 😉 do that mean I'll be the only HOS dev in Sweden?😂 Unlimited Power!!!!😂😂😂

**Comment by TheHappyKoala** [comment]
Hahaha, yes, as Sweden's only HOS dev you'll report directly to knugen! 

Nah, we'll see. Did my bachelor in the UK, and I'm a h00ge fan of British crime dramas as you know, but with Brexit and the resulting nonsense I'm not so sure I'd like to put up shop on that island once more. Besides, considering the rate at which people are killed in their crime dramas, I'd probably fear for my life once there, especially if I were to move to Oxford (Unge kommisarie Morse och Grantchester) which has probably seen more violence related deaths than Britain did in World War 2. And don't get me started on Midsummer... It's a veritable slaughter, there. 

There are some minor dev changes coming up, nothing big, but it will be quite an improvement on how we deal with scenarios now, will ping you when they've been committed! 

Oh, not that big on movies, but of course I had to go watch Ad Astra... And you do, too! Pretty cool movie. I think they used HOS for the CGI, though 😛 . Bastards. Where are out royalties?

**Comment by TheHappyKoala** [comment]
By the way, styled components actually make CSS a pleasure to write... Never thought I'd see the day when somebody would concoct a nice API for CSS, which only comes to prove you should never stop believing in a brighter future 🤣

**Comment by HugoGranstrom** [comment]
Haha 🤣 what an honor! Knugen himself of all people! 

Ahh right, brexit.... Had totally forgotten about that 😕 
Haha yes, it must be a real thrill living there in all of those crimes 🤣 

Great! 😄 I'll take a look at it 😉 Was the CGI so good? 😮 Better not mention royalties or they'll start asking us to pay them for their losses 🤣 

Styled components sounds lovely 👍

**Comment by HugoGranstrom** [comment]
The dev of Poliastro replied today:
>Thanks a lot for reaching out and sorry for the delay.
>I am so happy that poliastro helped you with your Gravity Simulator, thanks for letting me know :)
>Of course, adding poliastro to the README and the logo is OK with me. If you want to publish a success story that will appear in the poliastro documentation, feel free to send a pull request!
>https://docs.poliastro.space/en/stable/#success-stories
>I also added your project here:
>https://github.com/poliastro/poliastro/wiki/Projects-using-or-citing-poliastro
>Best!
>Juanlu

**Comment by HugoGranstrom** [comment]
I haven't gotten the new way of running HOS locally to work yet 🤔 It says `Listening very intently to 9000` in the terminal when I run `npm run jsonbar` but when I open `localhost:9000` all I get is a blank page with the text `Cannot GET /`. When I open the Console there are multiple errors about `Content Security Policy: Sidans inställningar blockerade laddningen av en resurs på eval (“default-src”).`. This time I ran ``npm i` beforehand so that shouldn't be a problem this time 🤣😅 
I'm going off to school now but I will try it out again tonight. I bet I have made one of those really silly mistakes again! 😅🤣

**Comment by TheHappyKoala** [comment]
Sweet stuff! 

Going to create an issue for giving credit to organisations whose resources we've used in the development of HOS, so I don't forget. 

Would you like to write up a success story about our implementation of poliastro and create a pull request for that?

**Comment by HugoGranstrom** [comment]
Great! 👍 I'll write something up over the weekend 😉

**Comment by TheHappyKoala** [comment]
Hahaha, it's not the most elegant setup, basically first you need to open a terminal window for running the static file server, and then you need to run npm start as usual in another terminal window. The localhost:9000 is just for serving the json files. Try localhost:9000/list.json and you should get a json file with references to all the scenarios. But to get HOS up and running, you just go access localhost:7000 as usual once you have the jsonbar running. Let me know if it doesn't work and I'll make some sort of screencap video

**Comment by TheHappyKoala** [comment]
And thankie!

**Comment by HugoGranstrom** [comment]
Ahh 😅 It works as it should 👍😄

**Comment by TheHappyKoala** [comment]
Phjew! By the time you graduate you'll also be able to put JavaScript dev on your CV 😄

**Comment by HugoGranstrom** [comment]
Haha let's hope so 😃 You learn more from your errors then your successes 😅

**Comment by TheHappyKoala** [comment]
Yea, failing is glorious, but in reality you only fail once you stop trying 😄 !

**Comment by HugoGranstrom** [comment]
Exactly!!!😉👌

**Comment by TheHappyKoala** [comment]
<img width="1228" alt="Screen Shot 2019-09-26 at 21 12 42" src="https://user-images.githubusercontent.com/23419647/65717794-709a6080-e0a2-11e9-8fe9-36eb47cbd44c.png">

5000 particles with a theta value of 0.3!!! And it runs smoothly, and the galaxy doesn't fly apart!!! Just gonna tidy up the code and figure out some gui crap but then Barnes-hut will finally serve the purpose it was meant to server 🚀 🚀🚀🚀🚀🚀🚀🚀

Created a separate loop for dealing with scenarios that have a "nBodyParticles" flag, and whowie it frees up resources. Question I'm asking myself is whether or not to add 15 000 or so massless particles to hang out with the 5000 particles with mass... As literal filler 🤣 Sorry, not making much sense here, but I'm so excited.

Awesome job, buddy!

**Comment by TheHappyKoala** [comment]
What do you think about whether or not to add massless particles? And what gui options would you like to see for barnes hut simulations? What would make em fun for you to screw around with?

**Comment by HugoGranstrom** [comment]
Woho! It looks amazing 😉😄 time to conquer the galaxy! 😎🚀 Optimizations for the win! 🎊

Hehe 😅 I think I would need a quick reminder of the difference between massless and massive particles. Do the massive particles affect all others gravitationally and the massless ones do not affect any others?

**Comment by TheHappyKoala** [comment]
Yes! Exactly. In the rings of Saturn scenario the ring particles only feel the gravity of all the masses in the simulation (sun, earth, saturn), but they don't exert any gravity on those bodies, or each other

**Comment by HugoGranstrom** [comment]
What I would like to simulate with BH is how a random distribution of matter develops with time. So maybe some kind of "Generate Random Distribution" GUI. And we could have different types of distribution (disk, sphere, cube etc).

**Comment by TheHappyKoala** [comment]
How should the initial conditions be set for those distributions... Like, velocities, more specifically? Or would you like a random distribution within some area, and then see what kind of clumps etc you get?

**Comment by HugoGranstrom** [comment]
Then it would be a great addition to make the graphics even cooler 😁👍 could/should we make the massless particles dimmer to show their difference? In case we get a bunch of it somewhere so people don't wonder why it doesn't attract the rest?😅

**Comment by TheHappyKoala** [comment]
Of course, no probs at all! My thinking is that teasing out structures should be easier with those in place

**Comment by TheHappyKoala** [comment]
And I think that's a great idea

**Comment by TheHappyKoala** [comment]
Could make it optional

**Comment by HugoGranstrom** [comment]
Yeah, some kind of randomness (within some kind of bound). Not anything scientific 😅 would be interesting to see what happens if we set the velocity of all particles to 0 🤔😂 my thought are totally pouring out right now, no blocks

**Comment by TheHappyKoala** [comment]
Yea, think I told you that my dream is being able to sort of simulate the evolution of the cosmic web; apparently matter is distributed in these thin filaments that are separated by these immense voids, where dark energy acts and pushes the filaments further and further apart. Coolest thing would be to be able to start with a random distrubition of particles where each particle is stationary and then just watch how structure forms as dark energy fights it out with baryonic and dark matter... But yea, how to simulate dark energy, remember us trying to figure that one out, but it was well tricky 😅

**Comment by HugoGranstrom** [comment]
Agreed 😉 makes it much easier to see. And more freedom to the user is never bad 😂👍

**Comment by TheHappyKoala** [comment]
And yes, I can relate to the whole thinking out loud thing you're talking about... It's like I suffer from intellectual tyfoid 🤣

**Comment by HugoGranstrom** [comment]
My memories are return again 😮😂 dark energy was a tough nut to crack 😅 did we come to any conclusions or were we still totally clueless? 

Your dream is shared my lots of people I think 😄 And you can help them accomplish it with HOS, what a thing! 😊

**Comment by TheHappyKoala** [comment]
Don't think so, no... But there has to be a way because there's no way those super simulations actually simulate space time, there has to be a degree of simplification involved

**Comment by TheHappyKoala** [comment]
<img width="800" alt="Screen Shot 2019-09-27 at 08 29 04" src="https://user-images.githubusercontent.com/23419647/65747121-f0efae80-e100-11e9-9249-a6a338e5f260.png">

**Comment by TheHappyKoala** [comment]
Started out as a disc with an ever so slight uneven distribution

**Comment by HugoGranstrom** [comment]
That's pretty cool 😁🚀 it does really bunch up towards the middle and there are traces of something looking like arms/filaments

**Comment by TheHappyKoala** [comment]
Yea, now we just need to simulate the emergence of two guys trying to simulate the emergence of, ehrm, two guys ad infinitum... If it's not turtles all the way down, it's two guys trying to simulate the universe all the way down

**Comment by HugoGranstrom** [comment]
🤣🤣🤣 haha that would be something

**Comment by TheHappyKoala** [comment]
Yea, let's hope we're not one NaN away from the Universe disappearing up its own exhaust pipe

**Comment by HugoGranstrom** [comment]
Yeah let's hope it simulation is well tested 😱 and have exception handling 🤣

**Comment by TheHappyKoala** [comment]
By the way, for a 2D simulation a quad tree suffices, no? Thinking that to be able to include even more particles, it would be cool to enable 2D simulations. Another thing I've been thinking about is that it might be a good idea to recycle particles that stray outside the bounds of the simulation by simply putting them on a random orbit around the center of mass.... What do you think???

**Comment by HugoGranstrom** [comment]
Yes exactly 😊👍 in 1D you would only need a binary tree 🤣
All of those sounds like good ideas 👍😄 2D is easier to visualize in my opinion

**Comment by TheHappyKoala** [comment]
Lol, Harmony of the Straight Lines... Doesn't sound quite as catchy, does it?

**Comment by TheHappyKoala** [comment]
But great, then we're on da same page

**Comment by HugoGranstrom** [comment]
Haha 🤣 na doesn't really have the right sound to it.

**Comment by TheHappyKoala** [comment]
Man, I'm gonna make it my mission in life to get permission to use the theme from the original Jurassic Park movie for the When Galaxies Collide scenario... https://www.youtube.com/watch?v=D8zlUUrFK-M

**Comment by HugoGranstrom** [comment]
Wow, yeah that would be pretty cool 😮😄🚀 The anticipation of the collision building up with the music is a must to experience! 

I have totally forgot about the Success story for Poliastro 😞 I will try to get it done next week when I get the time. Sorry for that 😅 Got carried away with doing simulations of electrical circuits in LTspice 🤣

**Comment by TheHappyKoala** [comment]
Totally, and I love pursuing weird goals in life 🤣 

No probs, take the time you need! I'm way behind schedule on pretty much every thing I've set out to do in the past month. Yet to write a draft for the article we discussed, Barnes-Hut keeps on presenting new challenges that I had not originally foreseen and, well, dibberyd00! 

Can't say I know much about electrical circuits but still I feel confident in saying that that sounds like extraordinary amounts of fun. Anything with spice in it makes me tremble with fear, though... What's it short for, anyways? Spice kernel this, SpicePY, Spice that.

**Comment by HugoGranstrom** [comment]
Life as a gravity simulator developer is hard 🤣

SPICE (Simulation Program with Integrated Circuit Emphasis), it is an open source electric circuit simulator from back in the late 1900s. It's a lot of fun fiddling with it. Much better then trying to connect circuits in real life 🤣 it all just becomes a mess of cables and a few components here and there. And if it doesn't work you have a really cumbersome debugging session in front of you 😅 So in that sense doing simulations is much easier because you can change things as you like. I must admit though that talking to outsiders about "spice" is a bit awkward 🤣

**Comment by TheHappyKoala** [comment]
Hahaha... Oh dear, after dabbling around with styled components I've decided to drop them. Awesome way of writing CSS when performance is not critical, but for this particular use case, the more components I migrated, the slower HOS would run, and it just got to the point where the dev experience of writing css the styled components way could no longer justify the loss in performance... Oh well 🙄
