### ISSUE TITLE
Add section for giving credits to organisations and resources

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#106]
Exoplanet archive, horizons, poliastro and so on... Something about standing on the shoulder of a pyramid of giants

**Comment by HugoGranstrom** [comment]
I'll think I should get going trying to cover the citation for all of the integrators. When doing the Sofspa10 I compared the coefficient for KahanLi8 with the ones on JuliaDiffEq and they weren't the same... But after much searching, I found that they proposed several eight order methods in their paper (Kahan & Li, that is) and I chose another one. So if not for anything else, I should do this for my own sake so I can find the source if anything odd happens with one of the integrators 😅

**Comment by TheHappyKoala** [comment]
Happy new year! 

Yea, just throw together a markdown file and we'll make it a page. I need to get to writing down some credits as well... It's important to recognize those that made your work possible 😄. Thinking of having a separate credits page for resources and then one for people that have contributed in one way or another

**Comment by TheHappyKoala** [comment]
Bringing the exoplanets back into the fold now... Once that's done, I'm gonna add procedurally rendered planets where the appearances of their surfaces depends on their mass and temperature, but then I'm gonna call it a branch and merge the shit out of it

**Comment by HugoGranstrom** [comment]
Happy new year 2 u 2 🎆 😄 

Yeah, it's really important, it's one of the pillars of making open source something people want to participate in. I'll throw something together over the coming days.
So like one Credits page for resources and a Contributions page for people?
Darrell, your attention to detail is amazing! 🚀 😉

**Comment by TheHappyKoala** [comment]
Yea, I was thinking one for contributors to the project, and then one for resources that have been used, like articles, 3d models, databases and so on... Does that make sense?

**Comment by HugoGranstrom** [comment]
Yepp, totally 👍 😄

**Comment by TheHappyKoala** [comment]
Sweet 🚀

**Comment by TheHappyKoala** [comment]
I'm like a child in the sense that when I discover something new, I have to play with it obsessively... Now, what have I discovered...? https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/migrate_to_gatsby/exoplanetArchive.js

I realise recursion is not as performant as just using an iterator, but damn, it makes so much sense. Heard people rant about it but I never bothered to look into it, but now I'm stuck. At the same time I'm a bit sad because there's no JavaScript engine that does tail call optimization 😢 

Somebody needs to write a babel plugin or whatever that takes recursive functions and transpiles them into normal loops, so we can have the cake and eat it, too.

**Comment by HugoGranstrom** [comment]
It's great to still have a piece of your child self in you 😉👍 you run no risk of becoming a boring, grumpy, old man 😅🚀 

It's so sweet when you can use recursion so elegantly so I think it's worth the performance lost imho if it make the code more readable and maintainable 😊

**Comment by TheHappyKoala** [comment]
https://gravitysimulator.org/credits

Aint that fancy of a credit page, but as I kept on postponing it, I figured it would be better to get the acknowledgements up there rather than delaying it because I wanted to implement some kick ass design. Here's the credits page file if you want to add some items of your own: https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/migrate_to_gatsby/src/pages/credits.tsx

**Comment by HugoGranstrom** [comment]
Nice work 😄👍 JuliaDiffEq is the only one I can come up with atm. I'm having my last examinations on Friday so in the weekend I'll try to get the integrator credits done

**Comment by TheHappyKoala** [comment]
Crossing my fingers for you, although I'm sure luck has nothing to do with your awesome exam results to be 😎

**Comment by HugoGranstrom** [comment]
Haha thank you Darrell 😊

**Comment by HugoGranstrom** [comment]
The exams went well :-) So now it's time to work a bit on HOS again 😄 
I've written the citations for the integrators now and it's quite a few so I think it would just clutter the credits page you've made. What do you think about having it as a markdown file in the repo and putting a link to "Credits for integrators" or something in the credit section? 😅

**Comment by TheHappyKoala** [comment]
Woho! Congrats, although I never had any doubts 😎 

I'll split the credits section up into 3 separate pages that will be rendered from markdown files :D. You can include that markdown file in the readme, though, as well, since I'm gonna include all the credits there, too. 

Gonna commit some fancy ass graphical improvements later on this afternoon, but now I'm off for some rare socialising over a coffee 😄 

Get back to you in a bit!

**Comment by HugoGranstrom** [comment]
Thanks, man! 😆
Great! I'll just drop it into the README for now so you can do as a please with it 😉😃 

Exciting 🚀🤖🚀 The graphics are dope as they are, and you're making them even better! 😲

**Comment by TheHappyKoala** [comment]
Textures take a bit longer to load now because they are higher quality, but zoom in on Earth and then the Moon... The resolution is insane, and I really like the new background... Like it's there, but it's not in your face like the old one. And while you're at it, zoom in on the new Sun 😄Tweaked the lighting as well, so you don't get those oversaturated blobs of light on the planets any more. 

It's going to make the spaceflight stuff that I have started working on again even cooler... Speaking of that, is there any chance you'd like to give calculating future orbital positions, using elements, a go again?

**Comment by TheHappyKoala** [comment]
https://gravitysimulator.org/solar-system/the-earth-system

**Comment by TheHappyKoala** [comment]
And look at Saturn's bands... https://gravitysimulator.org/misc/earth-spoils-saturn

So crisp!

**Comment by HugoGranstrom** [comment]
Wow! I'm star-struck! 🤩🤩🤩⭐🌟✨ That's amazing detail!!!! 🚀🚀🚀 And the background is perfection!

**Comment by TheHappyKoala** [comment]
Oh, and look at this 3D model: https://gravitysimulator.org/spaceflight/dawn-at-vesta

If you change camera focus to Dawn you'll see a model of the dawn spacecraft

**Comment by TheHappyKoala** [comment]
Glad you like the new background, because I felt the old one sometimes ended up obscuring what was happening in a simulation

**Comment by HugoGranstrom** [comment]
I'll definitely take a look at it again 😉😁 it shouldn't be too hard, I just gotta get a hang of which variables correspond to the variables in the litterature 😅

Good news regarding the SPH is that I have managed to miss that one of the courses I'm starting tomorrow is a course in Fluid Mechanics 😂😂😂 so I should definitely get a hang of it before the summer

**Comment by TheHappyKoala** [comment]
Wiiiieee 🌟 🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟

**Comment by TheHappyKoala** [comment]
And awesome!

**Comment by TheHappyKoala** [comment]
Should I create an issue and assign it to you?

**Comment by HugoGranstrom** [comment]
Go ahead 😉👍 

Dawn is cool as well 😀😄🚀

**Comment by TheHappyKoala** [comment]
https://github.com/TheHappyKoala/Harmony-of-the-Spheres/issues/115

There you go 😄 ! Have an awesome start to the week... Gonna watch The Capture now 😄

**Comment by HugoGranstrom** [comment]
Great! 😊👌

Have yourself an absolutely amazing week 😉😁 Sound great, I just watched the greatest version of Stad i Ljus by Per Andersson and Måns Zelmerlöw on Så ska det låta 😂😂😂 the most amazingly hilarious performance ever!
