### ISSUE TITLE
Get permission to use Jurassic Park theme for the When Galaxies Collide scenario

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#109]
https://www.youtube.com/watch?v=D8zlUUrFK-M

**Comment by TheHappyKoala** [comment]
@HugoGranstrom Might as well make this the designated issue for shit posting: new build is up! Unfortunately nothing Barnes-Hut related yet, but hey, as comfort, you can watch 90000 particles velocity verlet themselves into oblivion right [here](https://thehappykoala.github.io/Harmony-of-the-Spheres/#/category/Misc/scenario/When%20Galaxies%20Collide). Also made some changes to the layout... What do you think? Have I lost the plot? Wanted to make it more obvious to people that they can load Wiki articles related to each scenario within HOS, and I think I managed to accomplish that, at least... 🤔 There's a new splash screen, too... Bit more playful, wanted to go with comic sans, but stopped myself and settled for a compromise

**Comment by HugoGranstrom** [comment]
I'm having a lot of trouble running HoS right now. It freezes quite a lot 🤔 I'm running the web build. For example if I switch Integrator

**Comment by HugoGranstrom** [comment]
The layout seemed a bit crammed in the left sidebar 😅 the headers go into each other. 

Too much negativity from me here 😣 The new slash screen is really cool, I like how the clouds love across the screen 😉 and the galaxy simulation is awesome while it runs

**Comment by TheHappyKoala** [comment]
🙀 !!!

For which scenario does switching integrators cause HOS to freeze? And which integrator, exactly? Guessing you're switching to one with an adaptive time step, but there are no values for tol, max or min dt...

Ah, you're on a mobile device? If so, which one? And no, I love the fact that you're wiling to don a QA hat for a few moments to help spot issues 😄

**Comment by TheHappyKoala** [comment]
Ah, I can confirm that was the case, but feel free to double confirm... Patch is on ze way...

**Comment by HugoGranstrom** [comment]
The Inner Solar System was the one I had problems with (and your new fancy scenario) when I tried to switch to the all mighty RKN12 🤣 

This is on my laptop. It seems like there is no padding/margin around Misc, Spaceflight and Exosystems in the sidebar 🤔

**Comment by TheHappyKoala** [comment]
Any chance you could take a screen dump and paste it here?

**Comment by HugoGranstrom** [comment]
![image](https://user-images.githubusercontent.com/5092565/66597955-49fb2000-eba0-11e9-821c-6bd4aa128df2.png)

**Comment by TheHappyKoala** [comment]
Ah, this is why cache busting is needed, lol... Open the console and run localStorage.clear()

**Comment by TheHappyKoala** [comment]
You're not using chrome are you 😄 ? Only Chrome supports styled scroll bars...

**Comment by HugoGranstrom** [comment]
I'm running Firefox.... 😅

**Comment by TheHappyKoala** [comment]
<img width="561" alt="Screen Shot 2019-10-10 at 21 02 00" src="https://user-images.githubusercontent.com/23419647/66598394-3ef4bf80-eba1-11e9-898f-9abfbde24fb1.png">

**Comment by TheHappyKoala** [comment]
Sexy scroll bar; don't you just feel Chrome pulling on you as if though you were a ray of light within the event Horizon of a black hole?????

**Comment by TheHappyKoala** [comment]
And WebGL is faster in Chrome... But uh, I don't want to turn into one of those I'm using X so you should use X, too!

**Comment by HugoGranstrom** [comment]
I usually use Chrome for HoS but had Firefox open already 😅 🤣 Will not happen aggain

**Comment by TheHappyKoala** [comment]
Flippidiflipp! I was almost right. The error happens because for whatever reason some scenarios have tol values that are lower than the minimum allowed value for dt, so without having the code in-front of me I'm guessing stack size exceeded and hence the browser freeze

**Comment by HugoGranstrom** [comment]
Ah that makes sense 😉

**Comment by TheHappyKoala** [comment]
Fiiiixxxeeed. Damn. Really need to automate how scenarios are created 😅 

Did clearing your local storage solve the cluttered scenario tabs issue, by the way???

**Comment by HugoGranstrom** [comment]
Yes it did fix it 😉👍

**Comment by TheHappyKoala** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Comment by TheHappyKoala** [comment]
@HugoGranstrom The inevitable future of HOS: https://i2160.csb.app/

**Comment by HugoGranstrom** [comment]
Wow imagine something even remotely like that and I would be awestruck! 😮😄🚀🚀🚀

**Comment by TheHappyKoala** [comment]
Dream on: we both know the asteroid belt is not that densely populated 🤣. But yea, it's awesome, need to ask the author what license the code is under since that spaceship flame would be plenty cool to have for our rockets.
