### ISSUE TITLE
Fix the issue where the simulation freezes when you switch to an integrator with a variable time step when a simulation is running

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#112]

**Comment by TheHappyKoala** [comment]
@HugoGranstrom https://github.com/TheHappyKoala/Harmony-of-the-Spheres/commit/2f133059daaa2ca8f7d090d395f8a58e0d7849fd should take care of this issue... You can step on the integrator gas pedal now 🚀 Will push it to production later on today with some other stuff.

**Comment by TheHappyKoala** [comment]
<img width="795" alt="Screen Shot 2019-12-25 at 13 30 08" src="https://user-images.githubusercontent.com/23419647/71445519-cf5f8c80-271a-11ea-85d6-203a75a6162d.png">

Some pretty good numbers in the week leading up to xmas!

**Comment by HugoGranstrom** [comment]
Wait what?!?? 😮🤩 Nearly 10k visitors in a week!!!?? That's crazy! 🚀🚀🚀 And fantastic!! 
But where are they coming from? It seems like most of them hasn't just come from links on Reddit, Twitter etc.

**Comment by TheHappyKoala** [comment]
The old site got something like 70 k visitors in 2019, so our simulator isn't just collecting dust on the world wide web, haha. Most of that traffic came from social media, though; more specifically Hacker News, Twitter and Reddit. That's the main reason I decided to migrate the whole thing to Gatsby... To increase the amount of organic traffic we get, although it takes time for it to pick up, and most sites where you can share links make them no-follow, which is to say Google won't include them when calculating the rank of your site. 

Now that Gatsby is actually a thing the thing I'd like to focus on is to make it more interactive; make it possible for people to create their own scenarios and eventually share them, and then there's the space flight features which constitute a whole universe in their own right. 

Also gonna explore if there are any space sites out there that might want to use HOS as an embedded app when a new comet, exoplanet or what have you has been discovered. Shouldn't be trickier than wrapping it in an iframe. 

But yea, thank you for helping bring HOS to a whole other level in 2019, and here's to 2020 🚀 🚀🚀

**Comment by HugoGranstrom** [comment]
Wow that's huge 😮🤩 it must be an amazing feeling to know so many people has used something you have created! 😉😄 
The whole Gatsby thing sounds really promising :-) And if you get any space sites to use it, that would be a huge step forward in letting people finding and enjoying HOS 🚀😊 

This year has been the most fun and lärofyllda (google translate didn't really help me with "educational filled" 😂) I've ever had in programming and it's thanks to you and your efforts! The next few months one of the courses I'll have to take is an introductory programming course so I'm expecting to have some spare time to fiddle with HOS after my exams in the next few weeks. What is the thing you would want me to bring to the table the most? 😄

**Comment by TheHappyKoala** [comment]
Hehe, damn man, don't play with fire, asking me what I would like the most, that is 😄 

Uhms... Well... 😇 ... There is one thing that would be really nice, namely smoothed particle hydrodynamics: https://en.wikipedia.org/wiki/Smoothed-particle_hydrodynamics

With it, we could include way more realistic galaxy simulations, and we could create some pretty awesome collisions, rogue fragmentation and not to mention structure formation. Here's an example: https://www.youtube.com/watch?v=3JNNKQrfXzk

Here's a thesis that I found interesting: https://www.politesi.polimi.it/bitstream/10589/33101/1/2011_12_Pirovano.pdf

Universe Sandbox is developing this feature, as well. 

New stars, by the way, whose color is a function of their temperature, and they have dynamic surfaces with sunspots and what not: https://gravitysimulator.org/solar-system/the-earth-system

Change the camera focus to the Sun and zoom in and you'll see what I'm talking about. This will be especially cool for the exoplanet scenarios which I am yet to integrate with the gatsby setup since the stars will have the correct color... Low temperature stars will look reddish, and high temperature ones blueish. Still lots of room for improvement, but I think it's an improvement nevertheless, and collisions with the shockwaves work with these stars since they are spheres like all the other celestial objects in HOS. 

Oh, and planets have atmospheres again 😄 Really happy about that. And they don't look like crap from a distance like the old ones did. 

Added a higher res milkyway background with the new build, but I think I'm gonna revert it because it takes a million years to load 😢 Oh well!

**Comment by TheHappyKoala** [comment]
If smoothed particle hydrodynamics feels like too much of a project, I have an integrator and some other stuff that would be cool to include, as well.

**Comment by HugoGranstrom** [comment]
The new star and atmosphere looks great 😄🚀 

SPH should definitely be possible to implement but I must read up on it a bit first. It may be more of a project for the summer 😅 but I will do some research 😉😄 It seems really cool nonetheless 🚀 

In the meanwhile I could try to fix the other things to actually get some coding than as well (and you know how much I love integrators 🤩😂)

**Comment by TheHappyKoala** [comment]
https://www.vox.com/2015/5/26/8646675/apollo-10-turd-poop

I shouldn't find that funny, but the fact that it was an actual conversation and issue that astronauts had while in orbit around the Moon cracks me up 🤣 

I was looking at this list of integrators: https://docs.juliadiffeq.org/release-6.6/solvers/dynamical_solve.html

There's a 10th order symplectic one called SofSpa10. Is that something you'd be interested in looking into?

**Comment by HugoGranstrom** [comment]
Haha who could have imagined life being so shitty up there 😂😂

I looked up the code for it and if we are lucky we could reuse most of KahanLi8's code for it but with new coefficients. It's always fun with more integrators 😄 but it seems to be roughly half as fast as KahanLi8 so unless we have crazy low error tolerances I don't think it will be any faster tbh 😅 was there any particular reason for you wanting it or mostly for fun and the ability to say we have a 10th order symplectic integrator?😄😊

**Comment by TheHappyKoala** [comment]
My interest in it is more about its output being of a higher fidelity for long term simulations. One of the things I want to do is to run super long term simulations and record the results and then make gifs and or videos out of them. Like... Add a Neptune sized planet at 7 au in a fairly circular orbit and see how it affects the long term dynamics of the solar system... Maybe even add a feature where you can create clones with slightly different initial conditions and then see what kind of outcomes you get. But yea, it would be awesome to have a symplectic integrator of the 10'th order, won't lie about that 😅 🤣

**Comment by HugoGranstrom** [comment]
Ahh I get you 😉👍 Would be interesting to see a comparison between the symplectic integrators as well. If the order of accuracy matters at all for the general behavior of the system or if all we really need is Verlet.... 🚀😮

The clone idea seems really sweet and it would really show what it means for a system to be chaotic 😄

I've done some more investigation and it seems like it is similar too KahanLi8 so I should be able to commit it sometime tomorrow if it is cooperative 😅😄😂
