### ISSUE TITLE
A more general vector implementation

### ISSUE THREAD

**Issue by HugoGranstrom** [TheHappyKoala/Harmony-of-the-Spheres#12]
Having to specify what kind of vector is used is a bit inconvenient especially when for example trying to add one position vector and one velocity vector. I therefore propose instead of having a list of objects containing `x, y, z, vx, vy, vz`:
```` 
masses = [
    {x, y, z, vx, vy, vz, m},
    {x, y, z, vx, vy, vz, m},
    {x, y, z, vx, vy, vz, m},
    {x, y, z, vx, vy, vz, m},
]
````
If we instead assign a property called position and velocity to every body and both have the same form it would be easier to work with vectors generally instead of specific types of vectors. It could look something like this:
````
masses = [
    {
    position: {x, y, z},
    velocity: {x, y, z},
    m
    },
     {
    position: {x, y, z},
    velocity: {x, y, z},
    m
    },
     {
    position: {x, y, z},
    velocity: {x, y, z},
    m
    },
]
````
Then the position of a planet would now be accessed like this:

``masses[i].position``

and the old ``vx`` would be accessed like this:

`` vx = masses[i].velocity.x ``

Do you think this would be a good idea? I haven't look too much into how the vectors are accessed in the other part of the simulation but for general development I think this would make it alot easier to work with.

**Comment by TheHappyKoala** [comment]
I fully agree with you; it would be nice to simplify how vectors are handled in the code. Creating some helper functions for common vector operations would also make plenty of sense. 

As things stand now, the THREE.js Vector3 class is used for some operations in the physics utility functions module, and for vector operations related to the 3D animations. 

At first glance, it would make sense to just use this class for handling all the vector operations, but I would rather write something from scratch, for the simple reason that I don't want the physics modules to have any external dependencies. 
 
Needless to say, it would be a fun thing to do, as well. I could have used prepackaged solutions for pretty much everything in Harmony of the Spheres, but it wouldn't have been much fun, nor would I have learnt much, and those are my two main motivations for working on this project... Lols and learning stuff followed by the kick you get when you've figured something out :D. 

I'm going to start working on this, although progress will be gradual as there'll be quite a lot of refactoring to do. For one, I'll have to write a script automate changing how state vectors are specified in all of the scenarios... Not gonna do that by hand :D. I also have some other issues that I want to iron out in the meantime, so we could add this a couple of builds down the road. 

Would you be fine with continuing your work, on the issue relating to the development of an integrator with an adaptive time step, using the current setup (or lack thereof, depending on how you look at it)?

**Comment by HugoGranstrom** [comment]
I totally understand you, making things of your own and learning in the meantime is my main objective as well. :-D

I can imagine the refactoring taking a lot of time so don't rush it, keep the joy of coding.

I will give it a try, I have an idea for how to make it in a way that takes care of the vector types. If I can't get it to work I'll let you know in the issue and we can postpone it to the future.

**Comment by TheHappyKoala** [comment]
High-five and that sounds jolly good 😄 🤠 🚀

**Comment by TheHappyKoala** [comment]
There's still scope for improvements, but I'm closing this issue now as  there's now a module for working with vectors in a more abstract and high level way.
