### ISSUE TITLE
Dear Moon mission

### ISSUE THREAD

**Issue by Foxxy23** [TheHappyKoala/Harmony-of-the-Spheres#131]
when i try to play it it takes me to a black screen.

**Comment by TheHappyKoala** [comment]
Hey! Thanks for bringing this to my attention. I will look into it this weekend.

**Comment by TheHappyKoala** [comment]
@Foxxy23 

The dear moon scenario now loads as it should. However, it is still very much a work in progress and is, in my view, not particularly playable. I have created an issue where I have outlined the steps that need to be taken to make the scenario playable, and you will find it here: https://github.com/TheHappyKoala/Harmony-of-the-Spheres/issues/132

Today I'm adding a bunch of new exoplanet scenarios, but once I'm done with that I will start working on the starship scenario again.
