### ISSUE TITLE
Error regarding fsevent when running npm install

### ISSUE THREAD

**Issue by HugoGranstrom** [TheHappyKoala/Harmony-of-the-Spheres#43]
When I'm running ``npm install`` I get the following error:

```npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64```

It seems to have to do with the fact that I'm using Windows

Do you think there is a way to get around this?

**Comment by HugoGranstrom** [comment]
There seems to be a work around using:

``npm i -f``

but it is a bit off putting if a beginner would stumble upon this.

**Comment by TheHappyKoala** [comment]
Totally agree with you 😅 ! 

Should be fixed now; committed a patch that makes the fsevents package an optional dependency!

See[ this commit ](https://github.com/TheHappyKoala/Harmony-of-the-Spheres/commit/56c1ab60a5de198413d62107c764c355f29e12b1)for more info.

Could you please let me know if that solved the issue? 

Feel like such a stupid hipster on my Mac right now 🤣

**Comment by HugoGranstrom** [comment]
Works like a charm now :-D
