### ISSUE TITLE
Improve collision mechanics

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#55]
The only thing that is accurate about how collisions are handled in Harmony of the Spheres at the moment is where, on a sphere, the collision took place. This needs to changed, and bearing this in mind, the following features have to be introduced:

 * Elastic collisions
 * The direction vector of a collision impulse and the consequent trajectories of the ejecta needs to be modelled correctly: in simple terms we want to introduce billiard physics
 * If the kinetic energy released in a collision exceeds the bonds that hold the colliding objects together, they should both fragment. 
 * Things like shockwaves, and craters, which are to be added, should accurately reflect the energy involved in a collision

**Comment by HugoGranstrom** [comment]
Right, I was supposed to fix this a long time ago 🤣 good you're taking initiative. I hope my physics knowledge can be of help here. 

When you say elastic collisions, do you mean two planets will just bounce off each other or one shattering and the debris bouncing like billiard balls? Strictly speaking an elastic collision conserves the kinetic energy of a collision (no losses to heat).

**Comment by TheHappyKoala** [comment]
Hahahaha, I had totally forgotten about that. I was just playing around with the gravitational constant slider, causing a collision or two, which reminded me of how shoddy they are as things stand now, so I typed up an issue so that I wouldn't forget. 

The debris should bounce like billiard balls, and you're right, we should go for inelastic collisions. Totally sure you can help out quite a bit, here. My idea is that I whip up a prototype, and then maybe you can refine it? Not sure how to take the structural integrity of planets into account, for instance.

**Comment by HugoGranstrom** [comment]
Sounds like a plan 😉👍

If a big clump of rock would collide with a gas planet, say Jupiter, would there be any debris at all coming out of the collision as it's just gas in the outer layer?

**Comment by TheHappyKoala** [comment]
With reference to [this sequence of images](https://en.wikipedia.org/wiki/Comet_Shoemaker%E2%80%93Levy_9#/media/File:Impact_fireball_appears_over_the_limb_of_Jupiter.jpg): hell yeh :smile: 

To think that we've actually witnessed an impact of that magnitude... And several smaller ones since then; Jupiter is a cosmic vacuum cleaner :rofl:

**Comment by HugoGranstrom** [comment]
🤣 haha I'm defeated. You had even made a scenario of the collision. Guess it's like trying to dive in water when you land on your belly 😦🤣 the impact velocity plays a big role in it all. Jupiter would be welcome to me to do some cleaning as well 😅😂

**Comment by TheHappyKoala** [comment]
If Jupiter finds itself in need of some $, he has a clear career path set out for himself, I dare say. Imagine walking down the stairs in the morning only to bump into Jupiter cleaning the stairs with a broom :rofl:

**Comment by HugoGranstrom** [comment]
🤣 haha that would be a sight! Jupiter wouldn't have a hard time to attract customers at least 😜😂

**Comment by TheHappyKoala** [comment]
[Don't ask me why](https://pics.me.me/this-happens-once-in-300-years-only-mercury-venus-earth-26373273.png)

**Comment by TheHappyKoala** [comment]
Hey Hugo...

So, to get the velocity of the ejecta, I'm drawing on the following:

```
const getFinalVelocity = function (c, m1, m2, v1, v2) {
  return c * ((m1 - m2) * v1 / (m1 + m2) + (2 * m2) * v2 / (m1 + m2));  
}; 
```

It is my understanding that assigning a value of 1 to the c parameter means that the collision is perfectly elastic... Greater than 1 and we have an explosion on our hands and less than 1 gives us an elastic collision where some of the energy is converted into heat, noise and so on... If that is correct, what is a plausible value for c? I guess it depends on the composition of the planets and so on, but like, generally speaking? 

I'm getting some pretty neat results, though, so I'm hoping I'm on the right track. Definitely think I nailed the reflection vector stuff, although I need to add some randomness into the mix because right now you just get a blob of 3000 particles heading off in exactly the same direction, but that can easily be fixed, I reckon.

**Comment by TheHappyKoala** [comment]
Meh, doesn't seem to work very well, after all. Made the mistake of testing just one scenario, and it works well for that particular scenario, but for others not so much :(

You have any idea what the formula should look like given the masses of the two objects, their velocities and then the c coefficient?

**Comment by HugoGranstrom** [comment]
I can't say I immediately recognize that formula 😅 where did you find it? Does m1 and m2 stand for the masses of the two objects before the collision? As for a good value for c, what would be the most average material a planet is made of? Stone?

**Comment by HugoGranstrom** [comment]
https://en.m.wikipedia.org/wiki/Coefficient_of_restitution
In the section Speeds after impact you have a formula for the speeds of the two objects

**Comment by TheHappyKoala** [comment]
Hms, actually seems to work well for every scenario beside the odd ball that is the lunar free return trajectory scenario.

That's what m1 and m2 stand for, indeed. And yea, I guess stone would be a fair approximation. Maybe we could have one value for terrestial planets and one for gas giants. I found the formula here: https://sciencenotes.org/elastic-collision-two-masses-can-shown-exercise/

Looking at it I realise it's for elastic collisions, so not sure I can just add c like that, lol.

**Comment by TheHappyKoala** [comment]
Another thing I've noticed is that the closer the two bodies are in mass, the lower the velocity of the ejecta will be, and I guess this is to be expected given the approach of calculating the velocity vectors that I've chosen

**Comment by HugoGranstrom** [comment]
I'm afraid it can't be used like that saidly. c is a measure of how the ingoing velocities relate to the outcoing velocities, so we can't use it on the velocity we would get from a ellastic collision sadly. If one body is much larger then the other it would basically mean  V_outgoing = -c * V_ingoing for the ejecta. If the bodies are roughly the same size we would have a larger portion of the momentum go into the other body so the ejecta would get a lower velocity.

**Comment by TheHappyKoala** [comment]
I'm now using the formula on the wikipedia page you sent me:

```
            getFinalVelocity = function(c, m1, m2, v1, v2) {
              return m1 * v1 + m2 * v2 + m2 * c * (v2 - v1) / (m1 + m2);
            };
```

which I then invoke like so: ``` kin(0.8, looser.m, survivor.m, looser.vx, survivor.vx) ```

So two questions, I guess... Did I read and type out the formula correctly in the getFinalVelocity  method? Second... Does this make any sense whatsoever or am I guilty of chasing wild geese at the moment 🤣 ?

**Comment by HugoGranstrom** [comment]
That's odd, it's only that scenario that's being picky 🤔 Could it be a scale illusion? I don't know which other collisions you have watched but Earth is much smaller then for example Jupiter so that could be the illusion.

**Comment by TheHappyKoala** [comment]
It works swell when I smash Phobos and Deimos into Mars, for example, or the Neptunian moons into Neptune and so on

**Comment by TheHappyKoala** [comment]
I'm just starting to think this is not the way to go about it... I wanted celestial collisions to be simple, but it seems like they are not as simple as I would like them to be...

**Comment by HugoGranstrom** [comment]
The only thing is that (m1 + m2) should divide all the terms so a pair of () around all of them should fix it.

**Comment by HugoGranstrom** [comment]
Now my curiosity is sparked 😁 the velocities you use, looser.vx and survivor.vx. Are those just the x-component of their velocity or something else?

**Comment by TheHappyKoala** [comment]
The m1, m2 thing that you mention, what would this puppy - ```m1 * v1 + m2 * v2 + m2 * c * (v2 - v1) / (m1 + m2) ```look like with the pair of () that you said I should add around all of them? Didn't understand what you meant by all, haha. 

As for the velocities, they are just the velocities of the two masses the iteration before they collide... I do the same calculations for vy and vz, of course. 

Moments like these I wish I had opted for physics instead of economics at school 🤣

**Comment by HugoGranstrom** [comment]
I'm getting behind on messages 🤣 
Hmm... Phobos and Deimos ruins my theory 😂 what devils! Could it have to do with that the mass is so small somehow🤔? 
When your dreams collide with reality... 💥 Doing collisions the right way is quite hard and cumbersome so make every approximation you can make.

**Comment by HugoGranstrom** [comment]
My bad 😅🤣 I can't talk about "stuff" and expect people to understand what I mean. This is how it should be: (hope it's formatted, I'm writing this on my phone)
```
( v1 * m1 + v2 * m2 + m2 * c * (v2 - v1) ) / (m1 + m2)
```

**Comment by TheHappyKoala** [comment]
Maybe, Apollo 11 has a mass of 0, so that could very well be the issue. I think there's one flaw in the way I'm going about things now, though, which is that I'm calculating the velocity of the ejecta with the mass of one of the bodies that no longer exists... Each piece of ejecta is much smaller than its progenitor, so that needs to be taken into account, no, or am I out cycling?

**Comment by HugoGranstrom** [comment]
Hmm... It shouldn't make much difference because the mass difference is so big but let's me know if you see any difference. Btw, what was the difference when you added the parantaces?

**Comment by HugoGranstrom** [comment]
Yeah, it depends on how much if the mass that is being ejected respectively absorbed in the collision. If all mass was ejected this would hold but now we would maybe need to multiply it by the fraction m_ejected/m_original or something along those lines.

**Comment by TheHappyKoala** [comment]
Results appear to be the same, which is not necessarily a bad thing. Maybe I should factor in the change in velocity for the body that gets smacked, too.

**Comment by TheHappyKoala** [comment]
I'm gonna sleep on it and try implementing your suggestions tomorrow... Yawning way too hard, right now, so seems like the thing to do. Thanks for coming to the rescue and providing feedback... One thing is for sure, even in this state, the collisions are far better than they were before 🤣

**Comment by HugoGranstrom** [comment]
👍 interesting, I thought it would make a bigger difference giving us smaller velocities.

Sounds like a good plan, a good nights sleep should help solve some brain knots regarding this. I will do some pen and paper work tomorrow to see if I can sort this out.

**Comment by TheHappyKoala** [comment]
Page 26 of this [puppy](https://arxiv.org/pdf/1603.07151.pdf) is what we are after, I think...

**Comment by HugoGranstrom** [comment]
I think I have some ideas about how we can go about this. The main problem I had yesterday was how to deal with not all of the mass of the "loser" being ejected so now I make the following proposal:
We assume that the loser is made up of two parts, one heavy part with mass m and one lighter part with mass dm = k*m where k is the number of percentages of the mass that is being ejected. The small mass is the one that will bounce off the planet and eject, while the larger mass is the one that will merge with the other planet. Solving for the velocity of the ejecta gives different answers depending on in which order we assume the collisions take place. I, therefore, propose three different formulas that you can test to see which one you like the most.

1. "Kaboom": We assume both of the collisions happen at the same instant. Note the k I added in the parameters. For the formulas to not break down I think k should be smaller then 0.1 at least. 
```
getFinalVelocity = function(c, k, m1, m2, v1, v2) {
              return (m2 * v2 + m1*(1+k) * v1 - (m1 + m2) * c * (v1 - v2)) / (m2 + m1*(1+k))
            };
```
2. "Smash&Bang": We assume the ejecta collides with the planet before the heavy part does it.
```
getFinalVelocity = function(c, k, m1, m2, v1, v2) {
              return (m2 * v2 + k*m1 * v1 - m2 * c * (v1 - v2)) / (m2 + k*m1)
            };
```
3. "Ping Pong": We assume the collision between the heavy stuff happens first and that the small mass is so much smaller so it doesn't really do anything to the big mass.
```
getFinalVelocity = function(c, k, m1, m2, v1, v2) {
              return c * (v2 - v1)
            };
```

This was alot of physics talk so if I was unclear about something, don't hestitate to ask 😅 😉

**Comment by TheHappyKoala** [comment]
Oh, I'll go about testing these guys right away 🚀

**Comment by TheHappyKoala** [comment]
This does the trick:

´´´
//Get vx
Math.sqrt((2 * (0.5 * looser.m * (looser.vx * looser.vx)) / (looser.m / 1)))
´´´

You just rearrange the equation for obtaining the kinetic energy released by an impact and make velocity the dependent variable. To get the velocity of a fragment, whether it was a part of the impactor or the impacted body, you simply divide 2 * the kinetic energy by the mass of the fragment. In the pseudo code above you will see that the fragment has the same mass as the impactor, but if you replace the 1 with a 10, you will see that you get a higher velocity value, as would be expected for a lighter mass. 

There's no need to take the mass of the impacted body into account; gravity does that by itself by decelerating the ejecta as it embarks on its trajectory. 

All that is left now is to figure out how much energy actually goes into propelling one fragment, since some of it is lost, but even if it were not, it would not be concentrated in one point, but is distributed across the diameter of the impactor, and most of this energy will be concentrated in the center, and then it trails off towards the edges of the crater, so ejecta thrown up from the center of the crater will have a higher velocity than that which is thrown up from its perimeter. 

Our previous calculations will still be useful, though, for figuring out by how much the orbit of the impactor changes changes after being struck by some object (for most objects this is hardly noticeable, but still, fun). You could even simulate things like grazing impacts...

**Comment by HugoGranstrom** [comment]
Great! 👍😉 Can't wait to see some new collisions 💥 Does even work well for Lunar Return?

**Comment by dhnc** [comment]
Works well for every scenario 🚀 It's amazing to see the difference in velocity between different mass and impact velocity regimes! Oh, the mass of the ejecta particles plays a huge role, too... Right now I've limited it to 10 kg per particle, but playing around with these numbers you really get a feel for why it is so freaking difficult to launch heavy payloads into space 🚀 🚀 

What I need to get right now is basically how much energy goes into hurling fragments into the air and how the distribution of that energy is centered on the center of the crater and tails off when you move outwards... Shouldn't be too difficult to fix, but it needs to be done.

**Comment by TheHappyKoala** [comment]
I made a premature post earlier this week and discovered that no, that was not the case; the issue was that I was using the heliocentric velocity of the impacting body in my calculations and not the relative one, which of course meant that the kinetic energy of the collision was overestimated big time. It works now for all scenarios :D

**Comment by HugoGranstrom** [comment]
Awesome! Good catch, these kinds of algorithmic insights can be really hard to spot most of the times 😉👍

**Comment by TheHappyKoala** [comment]
Holy mother of Jesus... Done. 

How did the exams go??? If you're still in the middle of doing them, good luck!!! 🚀 👨‍🎓 

I'm going update the collisionTest scenario tomorrow so that you can see the improvements that have been made and then get back to integrating my new HORIZONS tool before starting work on fly controls and the ability to launch planets with your mouse where the longer you hold down the mouse button the faster the velocity of the planet. I've already figured out how to get this done so hopefully it's gonna be a very productive June 🚀 

Still need to implement total fragmentation, but momentum is conserved, ejecta velocity is a function of impactor mass and velocity, and the distribution of ejecta launch angles and associated velocities is now a-okay (higher angles and lower velocities the farther you get from the impact center). Gonna add a new collisions tab so that people can change parameters like the coefficient of restitution, mass of ejecta fragments and so on.

**Comment by TheHappyKoala** [comment]
Having said that, I'm closing this one for now as I don't plan to revisit the collision mechanics this month.

**Comment by HugoGranstrom** [comment]
Schoooolll'ssss out for summer!!! 🎉☀️ My exams went much better than I expected (without having gotten the results yet). 

The commits have been flying all over the place lately 😉 

Sadly I can't get the collisions to work 😅 It doesn't work at all with RKN12, it freezes upon impact. With RK4 the first collision works (but I see no particles) but then och the second collision it freezes. Have I just misunderstood you (or is there some piece of code you have forgotten to commit)?

**Comment by TheHappyKoala** [comment]
Oh, I pretty need to commit some other crap (got tonnes in staging, too much, really), will be done shortly 🚀

**Comment by TheHappyKoala** [comment]
Turned out it wasn't that much, but I committed some crap right now and for the master branch that should be it. You might have to run npm i and then after that you should be able to run npm run dev. The collisions test scenario is to be found under the what if category of scenarios... Notice how Ceres, although it is much less massive than all the other bodies, throws up a humungus ejecta cloud, which is due to its velocity. Also, check out the grazing impact of Mercury and how it affects the ejecta cloud... 

If it doesn't work or you bump into some issue, let me know 😄

**Comment by TheHappyKoala** [comment]
I'm running RKN12, btw, and it works swimmingly well 👍 Love the adaptive time step.

**Comment by TheHappyKoala** [comment]
Please let me know when you have pulled the changes as I need to do a reset --hard to clean up the shit commits... One of my favourite git commands, btw

**Comment by TheHappyKoala** [comment]
Ah, no worries, I sorted it out... Deleted the crap commits from the history books, added the .DS_STORE file extension to the gitignore file and deleted all the dsstore files from the repository.

**Comment by HugoGranstrom** [comment]
Works like a charm again 😄😉 it clearly behaves as one would expect now. Bang! 💥 And stuff flies all around. 

The Apollo's impact with Earth, no longer gives that huge cloud of particles, now it's barely noticeable, as it should be 👍😁

**Comment by TheHappyKoala** [comment]
Happy midsummer!

I have no clue what I'm doing, but I've added a Rosetta scenario and then I've finally figured out how to have a body orient itself according to the direction of its velocity, which is one of the final pieces of the puzzle before I roll out the space flight related crap that I have tucked away under a rock somewhere. It just really bothered me, for example in the lunar free return scenario, that the spacecraft model would not point in the direction in which it was travelling, which was why, I don't know if you noticed, Apollo 11 was represented by a huge sphere with a smily face saying I'm happy on it, but nada mass 😄. I've also added a chase mode for the camera which is kind of neat for both spacecraft scenarios and the up and coming asteroid death and doom scenarios I have planned (think following the asteroid as it comes tumbling towards the Earth Moon system as Earth gets bigger and bigger and bigger).  Moreover, I've added this logarithmic depth buffer feature which finally allows us to render everything from 1 m sized rocks to the Sun at the correct scale without running into shitty pants z-fighting issues; adding this is what allowed me to throw together the Rosetta scenario (at its closest point in that simulation Rosetta gets within 8 km of 67P!!! Oh, set the camera position to free and the focus to Rosetta... Pretty neat model, no? NASA has made models available for pretty much all spacecraft and with the above changes we can finally start using them in scenarios).

**Comment by HugoGranstrom** [comment]
Happy midsummer to you too! Have you seen any small frogs dancing today? 🐸 

How can I not have noticed a giant smiley flying through space 🤣 Chase mode sounds like it could be one h**l of a ride 😉 What would happen after the body being chased is destroyed? Just returning to defaults? 
Rosetta is a really neat mission. It can't have been easy to make it orbit 67P 😲 Nasa is fantastic in so many ways, especially giving away data like this.

**Comment by TheHappyKoala** [comment]
Hahahahaha... No, I don't really celebrate midsummer, to be honest. What about you? Done the whole dancing around the pole thing??? 

Right now when the body you chase is destroyed you just end up inside of the body that it collided with, but I'm going to change that so that you get a view of the area the object collided with. It looks really cool, though... It's like you're on an ICB'm before it dives towards its target. I'm thinking space warfare but I really need to stop shitting ideas all over the place and deliver on the ones I've already come up with 🤣

**Comment by TheHappyKoala** [comment]
Wiiieee... Got rid of the distance step and maximum distance crap when you add or modify masses... The maximum distance is now determined by the part of the simulation that is visible in the viewport and so is the distance step 🚀!!!

**Comment by HugoGranstrom** [comment]
I watched everyone else dance (including the pole, when gusts of wind came in). I prefer the food 😅 

👍 Space warfare would be awesome! 🤣 From a tool for showing off cool stuff in space to becoming a 3D Asteroid clone.
