### ISSUE TITLE
Good times with Mr. Barnes and Mr. Hut

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#56]
Finally figured out why my Barnes Hut galaxies and globular clusters would always accelerate apart as opposed to slowly evaporate; so this is a memo to myself to whip up the necessary code and start adding some related scenarios!!!!!!!!!

**Comment by TheHappyKoala** [comment]
@HugoGranstrom For the Barnes Huts scenarios, I'm thinking it makes the most sense to create an altogether separate scene module that is loaded if the scenario attribute particleSimulation is set to true. Those simulations won't have any of the camera logic and so on, so I'm thinking this is the way to go, rather than injecting yet more conditions into the scene module we currently have... Does this seem sane, to you? 

But first, a commit for the rotationorder of the ellipsecurve... ZXY it was, no?

**Comment by HugoGranstrom** [comment]
ZXZ was the order, with different rotations around the z-axis. The first time it's the longitude of aphelion, the second time the argument if perihelion. 

Sounds like a very sane idea, the Barnes Hut simulations are slow as they they are so all optimizations are welcomed here 😉

**Comment by TheHappyKoala** [comment]
ZXZ is not accepted... Y has to be specified, too. Maybe the way to do it is to simply not rotate y but maybe rotate z, then x and then z again??? Stating the obvious here, maybe 🤣

**Comment by HugoGranstrom** [comment]
That should work 😉 are you doing each rotation individually?

**Comment by TheHappyKoala** [comment]
Yea:

```
    this.rotation.x = degreesToRadians(axisRotations.x);
    this.rotation.y = degreesToRadians(axisRotations.y);
    this.rotation.z = degreesToRadians(axisRotations.z);
```

So that becomes: 

```
    this.rotation.z = degreesToRadians(axisRotations.x);  //Longitude of the ascending node
    this.rotation.x = degreesToRadians(axisRotations.y);  //Inclination
    this.rotation.z = degreesToRadians(axisRotations.z);  //Argument of periapsis
```

???????

**Comment by HugoGranstrom** [comment]
I don't know how the inner working of Three.js functions, but is the rotation done after each line? Or is everything calculated once per frame? In that case we would only get the last z-rotation 😅🤔

**Comment by TheHappyKoala** [comment]
I'm gonna head down the trail and error route and test for myself 🤣 Sophisticated it may not be, but sometimes it's the way to go.

**Comment by HugoGranstrom** [comment]
The hard life 😅 Kind of like using console.log instead of proper debugging tools 🤣. It's impressive though, to endure it 😉

**Comment by TheHappyKoala** [comment]
<img width="771" alt="Screen Shot 2019-07-27 at 20 34 29" src="https://user-images.githubusercontent.com/23419647/61998283-00755b80-b0ae-11e9-9d70-3026d2e05f05.png">

Think I fixed this... Couldn't align an orbit with those of Uranus's moons before, but now I can... Gonna see if I can reproduce some exact solar system orbits and if that's the case I'll send this pig flying

**Comment by TheHappyKoala** [comment]
And yes, that was one of my reasons for adding typescript... Although I can't see how debugging tools would be able to stop you from making a mess of transformations like this

**Comment by HugoGranstrom** [comment]
Awesome, if something needs to be fixed, Darrell can fix it 👍😄😉 if you would see some slight difference, you can try to switch the values for argument of perihelion and longitude (depending on which of the two types of Euler angles they are using)😅

**Comment by HugoGranstrom** [comment]
I must say that after having used Nim a lot this summer, that I have come to really appreciate typed languages, especially if used on conjunction with autocomplete and Intellisense. Really nice to not have to dig up the function definitions all the time 😄👍

**Comment by TheHappyKoala** [comment]
Maybe I asked before, but you use vscode???

**Comment by HugoGranstrom** [comment]
Jajamensan 😄👍 the perfect mix between lightweight and feature richness

**Comment by TheHappyKoala** [comment]
Fantastiskt! Hipp, hipp, hurra för vscode!!! Skulle nog hellre ha en usbsticka med vscode på tronen än knugen, faktiskt... Nog med svenska för idag 🤣

**Comment by HugoGranstrom** [comment]
Haha 🤣 to knock knugen out of his throne is some very seriösa grejer.

**Comment by TheHappyKoala** [comment]
Yea, I need to shutup or else I'll soon be joining A$AP in jail 🤣

**Comment by HugoGranstrom** [comment]
Wasn't you half American? Trump will make a call to Steffe and everything is solved 🤦‍♀️

**Comment by TheHappyKoala** [comment]
Dad's American yea, and while I wasn't born in the US, I do hold a US passport (got a Swedish one, too and I'm eligible for a Dutch one as well 🤣 )... Can't ever become president, though, because then you have to have been born on US soil 😢 🇺🇸

**Comment by TheHappyKoala** [comment]
How do I test the trajectory you were trying to simulate with da ellipse???

**Comment by HugoGranstrom** [comment]
Comment out the call for updateEllipse in the main loop and then the code is much like it is in the updateEllipse function. Get the Sun, Earth and Mars objects using the same way you get the primary. Then call planFlight() with tof = 1. I saved my code in a rather messy way in the lambert.ts file. Do a "toggle line comment" on the whole commented block in the bottom of the file. Everything that isn't commented out is my code I used 😅 it's a real messy, not proud of it at all. You will have to adjust the call to ellipseCurve.update(). You will have to import {planFlight, stateToKepler}  from lambert. Can send the complete code in an hour or so. 

This is really a mess 🤣 I remember now that this was what I was supposed to do before merging the pull request

**Comment by TheHappyKoala** [comment]
I'll wait for the complete code... Otherwise our dear spacecraft will probably suffer some sort of launch pad mishap 🔥 🚀 🤣

**Comment by HugoGranstrom** [comment]
Now I've got this sorted (hopefully 🤣)!

To run my test (draw ellipse between Earth and Mars) you have to do these modifications in the index.js:
- add this import: `import {planFlight, stateToKepler} from '../Physics/spacecraft/lambert'`
- On line 493: comment out `//this.updateEllipseCurve();`.
- Under it input this code:
```javascript
    this.ellipseCurve.visible = true;
    const scenario = this.scenario;
    const primary = getObjFromArrByKeyValuePair(
      scenario.masses,
      'name',
      scenario.primary
    );
    const earth = getObjFromArrByKeyValuePair(scenario.masses, 'name', 'Earth');
    const mars = getObjFromArrByKeyValuePair(scenario.masses, 'name', 'Mars');
    const tof = 0.5;
    const k = primary.m * 39.5;

    const vs = planFlight(tof, earth, mars, primary);
    const initVelocity = vs[0].initVel; // if you want to launch a rocket, this is the initial velocity you want to set.

    // below is ellipse drawing code
    const keplerElements = stateToKepler(earth, initVelocity, k);
    const scale = scenario.scale;
    const ellipse = getEllipse(keplerElements.a, keplerElements.e);
    this.ellipseCurve.position.z =
      (this.rotatingReferenceFrame.z - primary.z) * scale;
    this.ellipseCurve.update(
      (this.rotatingReferenceFrame.x - primary.x - ellipse.focus) * scale,
      (this.rotatingReferenceFrame.y - primary.y) * scale,
      ellipse.xRadius * scale,
      ellipse.yRadius * scale,
      0,
      2 * Math.PI,
      false,
      0,
      { x: keplerElements.omega, y: keplerElements.i, z: keplerElements.argp }
    );
```

**Comment by TheHappyKoala** [comment]
Sweet, thanks!

**Comment by TheHappyKoala** [comment]
```
    const initVelocity = vs[0].initVel; // if you want to launch a rocket, this is the initial velocity you want to set.

//HELL YEA I DO

```

**Comment by TheHappyKoala** [comment]
Lol, somebody tell that ellipse to get off the acid

**Comment by HugoGranstrom** [comment]
🤣🤣🤣😂😂😂

**Comment by TheHappyKoala** [comment]
So the vectors are all correct but the ellipse drawing is what's f'ed up? As in if I gave a mass these vectors it would head off to Mars?

**Comment by HugoGranstrom** [comment]
I hope so, haven't tried it yet 😅 but if anything work, it should be the vector. Remember that this won't take it from Earth to Mars because we use both positions at the same time, but it should pass the spot where Mars was.

**Comment by TheHappyKoala** [comment]
Ahhhhh, got ya!

**Comment by HugoGranstrom** [comment]
If you want to simulate a trip from Earth to Mars, replace `const mars = {x, y, z}` with the position of mars 0.5 years into the future

**Comment by TheHappyKoala** [comment]
So tof is the time it takes the rocket to get to mars, earth is earth in its current state position and velocity wise and mars should be a future state of Mars that we will use horizons to figure out????

**Comment by HugoGranstrom** [comment]
Correct 😉

**Comment by TheHappyKoala** [comment]
Ah, so using Euler for this setup is not an option 🤣 ! Thanks for explaining, gonna start toying around with it now and get that ellipse to rehab, detox the shit out of it so that it will behave the way an ellipse ought to.

**Comment by HugoGranstrom** [comment]
The ellipse tuning was the reason I used both position at the same time so we had something to compare it against 🤣😅 hope Mr. Ellipse will friskna till snart

**Comment by HugoGranstrom** [comment]
Woke up and realized I haven't told you what tof stands for 🤣😅 time of flight

**Comment by TheHappyKoala** [comment]
Hahahahahaha... I can't imagine a worse nightmare, but no, I managed to guess it 🤣

**Comment by TheHappyKoala** [comment]
Is there a reason for why you get the initial velocity of the rocket in the loop, which means it's set every iteration?

**Comment by HugoGranstrom** [comment]
To make a cool animation 🤣😅 I put it inside an `if (scenario.ellapsedTime  == 0) ` before but it wasn't as fun

**Comment by TheHappyKoala** [comment]
Ahhhh 🤣 I know the feeling, I'm such a sucker for cool animations... Hence the star shader which nobody will see unless they zoom in on the star, hahahaha.

One more question... The planFlight method that gives you the velocity your rocket needs, is there a way to get its starting position in there, too???

**Comment by HugoGranstrom** [comment]
All the much sweeter for the ones who discover that gold nugget 😉

I'm probably a bit dozy still, but don't you already know the starting position? It's what we called `earth` above 😴

**Comment by TheHappyKoala** [comment]
Ahhhhhhhhhhh.... I thought it would be Earth + 200 or so km, i.e lower earth orbit, but cool, then I'll turn off the collisions and let my rocket roar :D

**Comment by TheHappyKoala** [comment]
I on the other hand feel very 😴

**Comment by HugoGranstrom** [comment]
Aha 😅 nothing such fancy yet. Pure starting positions for now, and only between planets. If you wanted you could replace `earth` with an arbitrary starting position, so you don't have Earth's gravity disturbing your ellipses in the start

**Comment by TheHappyKoala** [comment]
That was going to be my next question 🤣 //Darrell Open Book Huffman

**Comment by TheHappyKoala** [comment]
Holy GUACAMOLE

**Comment by TheHappyKoala** [comment]
This is so, so awesome, Hugo

**Comment by TheHappyKoala** [comment]
<img width="835" alt="Screen Shot 2019-07-28 at 09 22 42" src="https://user-images.githubusercontent.com/23419647/62003582-56331d80-b119-11e9-94de-5f7ce58705b9.png">
<img width="772" alt="Screen Shot 2019-07-28 at 09 23 00" src="https://user-images.githubusercontent.com/23419647/62003589-63e8a300-b119-11e9-8e08-7c4f71f66109.png">

I decided to go to Jupiter, or when Jupiter was when I started the simulation 🤔 🤣

**Comment by HugoGranstrom** [comment]
😯 now we're talking! 🥳

**Comment by TheHappyKoala** [comment]
Hell yeh! That is absolutely amazing. Nothing short of it. We're gonna do this properly and I'm gonna develop a cockpit with pointerlockcontrols so that the user can not only look at the direction the craft is travelling in, but out of side windows, too. Here's [an example of pointerlock controls](https://codepen.io/tembling/pen/reZjEw).

**Comment by TheHappyKoala** [comment]
Sorry for going a bit bonkers here but something like this deserves that and nothing less

**Comment by TheHappyKoala** [comment]
Coasting through the Jovian system while taking a look at a crescent Europa through the port window... It would be a bit of work, but nothing I couldn't do technically

**Comment by TheHappyKoala** [comment]
Will we be able to take perturbations from the starting body into account???

**Comment by TheHappyKoala** [comment]
OMG... I just planned a trajectory to Mercury, and instead of flying in straight, it took me out to Saturn on a mega elliptical orbit which then plunged me to Mercury (2 year travel time). Not very practical if you want to go into orbit around Mercury and need to brake your craft, but yea 🤣

**Comment by HugoGranstrom** [comment]
That sounds amazing! Blazing through the Solar System inside a spacecraft cockpit 😉😄🚀 Can we expect a VR version in the future? 😅 

planFlight is just an auxillary function in my idea of a autopilot, so the first thing it will do is to go around in a very large elliptic orbit around the starting body (that crosses the final position). Then when it has come some way from the starting body we run planFlight again but with the Sun as the central body instead of the starting body. So we will be calling planFlight maybe 10 times during a mission and doing burns after each one so that we get the desired velocity. 

Hehe 🤣 you can configure it a bit if you want. If you pass M to planFlight you can choose how many revolutions you want to make before arriving (have no idea what it means though 😅🤣). Test it out and see, the default is M = 0. We will probably want to choose the one that has the smallest difference in starting and final velocities 😄 (finalVelocity is also returned from planFlight)

**Comment by HugoGranstrom** [comment]
Would be interesting to see if the trajectory changes a lot if we adjust the travel time just by a few day 🤔

**Comment by TheHappyKoala** [comment]
Oh, that makes perfect sense, in the sense that that is how actual missions are done, with sequential trajectory course manoeuvres. I'm meeting up with an old buddy for a cup of coffee in a bit, but once back home I'm going to aim for the leading edge of Jupiter and give myself a good old fashioned gravity assist 🤣 

And yes, we should develop a VR friendly interface, at least for the spaceflight stuff, to begin with. Cool thing is that I have a starship, bfr, what ever you wanna call it model that looks exactly like the one in this ["artists impression"](https://media.wired.com/photos/5d2d09439a6762000863bf47/master/pass/Science_Starship_43895099655_64490f5eed_k.jpg), and I think that would be a pretty cool spaceship model to begin with. It even has all the rocket stages (you can include or exclude them).

**Comment by TheHappyKoala** [comment]
Before I bounce, one last question... Is there a reason for why you said it's only for planets and not for asteroids??? I just intercepted Pallas 🤣

**Comment by HugoGranstrom** [comment]
Bad phrasing from my part 😅 mean only non-advanced manoeuvers. Feels like the risk of hitting (or being pertrubated by) Jupiter is a great risk if we aim for it's moon for example. Lone objects should be no problemos though 😄😉 but please try and prove me wrong, would be awesome 👌😁

You are like a magician's hat, you can pull out all kinds of cool stuff 😎  it looks fantastic. Just the thought that we could have something as cool as this running in the browser blows my mind time and time again 🤯😵🤣

**Comment by TheHappyKoala** [comment]
Yea, it's crazy how far browser technology has come, and the breadth of experiences you can create on the web, that are available to everyone regardless of which device they are using. An installation isn't even required! 

Quick question: would you be fine with me starting development on all the madness I've been ranting about??? I'm itching 🤣 Know you still have work to do and I have no plans on rolling things out to prod, but I just feel like this needs my _attention_ 🤣

**Comment by HugoGranstrom** [comment]
The installation part is very important, we don't have to deal with distributing anything other than a URL, really 😎

Sure, go ahead! I'm in no power to stop you either way 😜 You do what you feel is the most fun, and this project will reach heights no one could imagine 😉 

A heads up: I won't have access to a computer for the next 1,5 weeks so is there anything you urgently need from me to be able to do your stuff? Won't go totally offline though, will have my phone still but it's a pain to do any programming on it 🤣 (Can't belive how I managed to learn to program in Java on my 4 inch phone back in the day 😅😂). I can be a bollplank for your ideas though 😃

**Comment by TheHappyKoala** [comment]
<img width="629" alt="Screen Shot 2019-07-28 at 20 02 30" src="https://user-images.githubusercontent.com/23419647/62010987-aa1e2080-b172-11e9-96f9-9c867c437119.png">

Hahaha, thanks, but I think it's much nicer to do things by consensus... What a Swedish thing to say, but yea 🤣 ! 

Cheers for letting me know, and enjoy the hell out of your little break or whatever it is that you're getting up to 😃 . I'll keep you updated on my progress and will definitely ask for you feedback when I get to developing the gui. But don't stress getting back to me! 

Hahaha, that's hardcore. I have a bit of an inferiority complex because people are always telling me about how they started coding their atari at the age of 12, or something along similar lines, and I only got started three years ago 🤣 Better late than never, though! 

There's our spaceship, in any case. Need to figure out how to rotate it in Blender but that shouldn't be too difficult.

**Comment by TheHappyKoala** [comment]
<img width="1055" alt="Screen Shot 2019-07-28 at 21 16 41" src="https://user-images.githubusercontent.com/23419647/62011776-0e45e200-b17d-11e9-8408-2b8e2a905d4f.png">

Fixed it!

**Comment by HugoGranstrom** [comment]
Haha true 😂 we are acting more swedish then we realize 😅

Thank you 😁 will be back fresh and ready to continue with my space trip agency 🤣 

Another way to view it is that despite of your different origin in coding, both your paths led to the same place so are they really that different? 😉 It's the present and what you can do now that counts, not what you could do when you were in middle school. You can clearly handle a lot of things that many who program for a living wouldn't be able to do. Be proud of where you are now, Darrell, and be even more excited for what you can become 😊 

Whoop whoop! Am I watching Interstellar or what?! 😮🚀 Now I'm longing even more to take a trip through our Solar System if I get to ride one of those 🤤

**Comment by HugoGranstrom** [comment]
Saw this when surfing the web today: https://www.sciencedaily.com/releases/2019/07/190729111328.htm 

TESS found new planets around a star TOI 270. They published this the 29th July. Thought this could serve as a guideline for how long it takes for new planets being added. How long do you reckon it will take?

**Comment by TheHappyKoala** [comment]
Hey Hugo!

Thanks for your kind words. You're totally right; in the end the race is only with yourself! But yes, being that I write code for a living, I know for a fact that there are things I can do that people that program for a living can't :rofl: I think what it comes down to, when you're self-taught, is imposter syndrome, especially when you work with people that have degrees in computer science. What I've come to realise, though, is that my strength is that I'm not a programmer by training, but by love, and my hunger for knowledge is insatiable, which keeps me pushing and pushing. I think it was Napoleon that said that energy beats genious! 

Yea, I saw that, and then I headed over to check if the scenario was there and it wasn't, which prompted a DUDE WHERE'S MY PLANET?! moment on my part, but as it turns out they only add them once a week, Fridays I think. 

Got another assignment which is also for a restaurant app (how many of them can there possibly be) and I'm on a super tight deadline, so haven't done much since you left for your holidays extravaganza, but tomorrow I'll probably be able to wrap it up and get back to working on HOS. Quick question about HOS: the stateToKepler method would actually fit with some other celestial mechanics related methods like the vis-viva, elements to vectors etc that I'm planning on wrapping together in a utils class; you fine with me extracting it from your lambert module??? Once this has been done, we should be able to kill off the physics utils module: yay!

**Comment by TheHappyKoala** [comment]
Regarding the spacetravel stuff that we are introducing, I'm thinking about introducing two modes of space travel: one where you have a craft with infinite fuel, and one where you have a finite amount. For the finite version, I'm thinking it would be super awesome to use the rocket equation to calculate if the craft has enough fuel to pull off a given lambert trajectory, orbital insertion burn or what have you, to make things a bit more realistic and dare I say it game-like. You think that's a good idea????

**Comment by TheHappyKoala** [comment]
:rofl: The exoplanet archive has updated their database with the new planets, but the caching I introduced is a bit whiffy and needs to be fixed: you need to run localStorage.clear() in your console for the new systems to show up. Fixing it tomorrow!

**Comment by HugoGranstrom** [comment]
Very nicely explained, we do this not because we must but because we love it 🤗

Ahh I see, that seems reasonable. Will check it out when I get hold of a mobile browser with a console 🤣

Go ahead, do what must be done and copy paste what must be copy pasted 😉 I have yet to visit a restaurant with an app (except the big food chains). What kind of functionality do they generally want? 

The two modes sounds really good to me, mainly because I can ignore the second mode for now 😅🤣 bad Hugo, bad Hugo 🤭 Game like elements are more than welcome, and do you know what games need? Controllers! Have you had any thought of what the space bar will be in your future game plans? I have a idea: start/pause

**Comment by TheHappyKoala** [comment]
While a boring day at work, or ten minutes by the bus stop, is inevitable, that ought to be our leading light for anything we do in life, especially the things we _choose_ to do 🚀 !

Ah, man, when you write that you don't have access to a browser with a console, I can't but help picture you dangling from a rope attached to a cliff face somewhere in the Himalayas, possibly with some bad guys in a helicopter approaching you, but you're about to down their chopper with your trusty ice axe which you have tucked into your belt 🔨 🚁 🤣 

The app in question is this system where the users have installed the app on their phone, and they can use it to place orders, and then the waiter wears a smart watch that receives the orders.  I'm just contracted as a freelancer so I'm not personally invested in this product, but apparently they've landed quite a few contracts with restaurants around Sweden, although I'm skeptical and have told them so (I just don't know any better, but then again they only need me to code (and not the whole app, just some payment system integrations), not to tell them whether I think their business plan is viable or not 🤣 ) since it relies on having users install their particular app, and with coverage in only a couple of restaurants here and there, I struggle to see the whole thing taking off. You need network effects for something like that to succeed. 

Once I've wrapped up this assignment I'm gonna look for 9 - 5 employment again. Quit the job I started in March at the end of June after they cut a quarter of the workforce and announced that the company had not more than a year left on with its current investor capital. It was a peculiar journey as none of this was mentioned during the interviews 🤣 . Oh well, now I've learnt to do some research before signing a contract... Knowledge is power 🚀 🤣 🤔 

Damn, I need to stay on topic. This is supposed to be about Barnes and Hut, no??? You say bad Hugo, and to that I say BAD Darrell.

**Comment by TheHappyKoala** [comment]
Hugo, I am hereby endowing you with full authority to tell me what shortcuts to assign to keyboard keys 🏆 ! I've never planned on integrating the keyboard as I've been more focused on creating an experience for phones and tablets, but it's easy stuff to do some keyboard bindings, so let me know 😄 

Also, how about creating a dedicated issue for shit posting so that our actual technical discussions don't get lost in reflections on life or stuff that we otherwise find interesting or awesome 🤣 ?!

**Comment by TheHappyKoala** [comment]
By the way, lol: https://wiki.kerbalspaceprogram.com/wiki/Maneuver_node

That's what I have in mind with the cheap ass event system that I wrote. Also, on a related note, I think it makes more sense to to get future positions by iterating the simulation forwards in time as any error is taken into account, then... Horizons will have a super important role to play in setting up the scenario you want to simulate, though, so that still has to be done 🚀

**Comment by TheHappyKoala** [comment]
Hilarious... I just had my spacecraft get captured ballistically by Jupiter 🤣 

It works awesomely well, the lambert solver. Only bug that I've uncovered and I guess it's typical that I would uncover it is that if I set the destination to be the same as the central body, things go poop, and the same goes if you set the position vectors to 0, 0, 0. Setting them to {x: 0.0001, y: 0.0001, z: 0.0001} works fine, though. And yes, Hugo, I wanted to crash my spacecraft into the Sun 🤣 And so I did with the last set of position vectors 🚀 🌞

**Comment by TheHappyKoala** [comment]
Thinking out loud a lot today... Wouldn't the easiest way to get future positions be to convert state vectors into orbital elements and using those figure out where the body will be at some future point in time???? stateToKepler to the rescue!!! Need to get the true anomaly and convert the orbital elements back into vectors but that shouldn't be too tricky.

**Comment by TheHappyKoala** [comment]
Hms, I think statetokepler gives me the true anomaly, it's vi, right? If so, wow, almost there 😄

**Comment by TheHappyKoala** [comment]
Is there any chance this is the eccentric anomaly?   

const E = vNorm ** 2 / 2 - mu / rNorm;

**Comment by HugoGranstrom** [comment]
🤣 hahaha exactly the situation I'm in! That doesn't seem like something that's going to fly, but as long as they pay you... I guess the "safety" of a ordinary job is quite valuable now that we potentially are moving in towards a low conjuncture (?). 

Keyboard controls should only be an alternative way of doing things that already is possible in the GUI. Haven't really come up with anything other than pausing/starting the simulation 😅 

Haha 🤣 we really do need a separate thread for these kind of things 😅 should we open an issue with a funny name and then close it so people don't stumble upon it by mistake when looking for serious issues 🤣😅

**Comment by HugoGranstrom** [comment]
Simulating into the future gives more flexibility on what kind of scenarios we can do spacecraft stuff in. With Horizons we are limited to only the real solar system. Now we can do whatever we want. But as we want to run this simulation multiple times during a run we would want it to be as efficient as possible so I would suggest that we only use RKN12 for these intermediate simulations. What do you think of that? There is no use in using Euler for it if the user is using it, sure we would get to the destination but so would all integrators do. It's more interesting to use the most accurate for getting the final position and then comparing the different integrators to see which ones gets us there. 

Regarding the use of orbital elements for getting future positions, it would really only work for bodies or orbiting the Sun, I think. If we for example would like to go to Titan, we would need to do it first for Jupiter and then in some way do the same for Titan but I'm not entirely sure how that would work. `vi` is the true anomaly 😉 you are granted permission to rename it 🤣 the symbol for it looked like a funky "v" so tired Hugo go the lazy route. E is the *specific orbital energy*. 

Is it the first crash coordinated by Lambert?  🤣 Poor Jupiter, we crash all kind of things into it. Iterative solvers can be a bit picky sometimes around certain points and 0, 0, 0 must be one of them.

**Comment by HugoGranstrom** [comment]
You can calculate the eccentric anomaly from the true anomaly: https://en.m.wikipedia.org/wiki/Eccentric_anomaly

`tan(E) = sqrt(1 - e^2) * sin(θ) / (e + cos(θ))`

**Comment by TheHappyKoala** [comment]
Screw the orbital elements... Let's go for precision with perturbations from other bodies taken into account 🚀 !

And, this is so cool, the first time I've found an actual use case for this crap, but JavaScript allows for multiple threads, so you don't lock up the main thread with a bunch of a expensive computations and make the whole app unresponsive as a result - https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers. So when a future state of the simulation is requested, I'll pause the simulation, get the loading screen saying loading future simulation state and then when it's done unpause and remove the loading screen.

**Comment by TheHappyKoala** [comment]
But yea, I was thinking exactly the same thing; limit the choice of integrator to RKN12 for optimal precision, which is a must-have when you're trying to simulate these kinds of things.

**Comment by TheHappyKoala** [comment]
Lågkonjunktur in English is recession 😄 ! Developers have it really well, though, we're in crazy demand and I've never had any issues finding work, not even when I'd just been coding for a year and applied for my first job 🤣 I keep on telling my friends that are stuck in jobs they don't like to learn how to code but none of them ever do... I think they could, but they don't put in the effort ☹️. 

So don't worry about your career prospects 🚀 !  My biggest issue with freelancing is that working from home isn't all it's made out to be. It's nice to have a wfh day once a week to be able to take care of stuff around the house and so on but all the time kind of makes it hard to separate work from your personal space, not to mention that I do enjoy sprinkling lame jokes left and right as much as I enjoy shit posting where I shouldn't be shit posting 🤣

**Comment by HugoGranstrom** [comment]
Will be interesting to see how much faster these smaller simulations are then a ordinary, because we won't have to render and do all the graphics calculations?

**Comment by TheHappyKoala** [comment]
Indeed, and we're not limited to 60 iterations a second, which is the limit set by request animation frame

**Comment by TheHappyKoala** [comment]
So if you think it would be interesting we could perhaps use them to fast forward in time?

**Comment by HugoGranstrom** [comment]
THAT!!!! Is a BRILLIANT idea!!! 😱😉👌😍

**Comment by TheHappyKoala** [comment]
RIght on! Två flugor i en smäll, då 😄

**Comment by HugoGranstrom** [comment]
Perfect 😉👌

Hehe.... My financial vocabulary isn't what it could be 🤣

Good to hear my prospects are looking good 😄

**Comment by TheHappyKoala** [comment]
Didn't go about it in quite the way I'd planned, but running oumuamua at the normal speed I'm able to get to 400 years in one minute instead of the 22 without fast forwarding. And my computer doesn't melt either and no stack sizes are blown, so cheap as my solution may be, I'm kind of happy with it.

**Comment by TheHappyKoala** [comment]
And there's no loss of accuracy

**Comment by TheHappyKoala** [comment]
With the animation on it's still so fast that I can see the movement of the solar system's barycenter and the orbit of Mercury precess like a mad man

**Comment by TheHappyKoala** [comment]
Gotta say that I'm less concerned about optimizing the scene module by introducing a loop or two to deal with the camera crap, now. There's plenty of padding performance wise to handle that... I think, or have I spent too much time throttling and dethrottling today 🤣 ?

**Comment by TheHappyKoala** [comment]
<img width="1440" alt="Screen Shot 2019-08-03 at 22 38 45" src="https://user-images.githubusercontent.com/23419647/62416678-89a50900-b63f-11e9-9bc9-aa9b9f6de04d.png">

Maybe I should go easy on the decimals a bit 😛

**Comment by TheHappyKoala** [comment]
After yesterday's insanity something palatable is starting to emerge... Makes sense both code wise and in terms of UI. 

Something I've been thinking of, when you're setting your trajectories, the time step should probably be slowed down to say 1 second? Otherwise launch windows for a Mars Hohmann transfer will just come and go like lightning... 

A lot of UI development going into this, but it's fun 🚀

**Comment by TheHappyKoala** [comment]
UI and state management code is almost done and will be pushed tonight, but here's the trajectory cruncher, a web worker that spits out a trajectory: https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/d3671147c3ef9d1cbeb75a864ab71ee35d67f0f8/src/js/Physics/spacecraft/trajectoryCruncher.js

Not quite sure how to work with web workers in typescript, so for now it's a js file, but once I figured that one out I'll add types and stuff.

**Comment by TheHappyKoala** [comment]
Closing this issue; will recreate it!
