### ISSUE TITLE
Develop a Lambert Solver

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#59]
The goal is to include spaceflight in future versions of Harmony of the Spheres. One important aspect of spaceflight is trajectory planning, which is to say figuring out how to get your craft from mass i to mass j given a time constraint. In celestial mechanics, this is called [Lambert's Problem](https://en.wikipedia.org/wiki/Lambert%27s_problem). 

With the rocket equation and the quantities associated with it, the user will, with the Lambert Solver, be able to figure out a suitable trajectory for their spacecraft given its thrust and fuel budget. The user would be able to do this in real time, or use the event planning capabilities of Harmony of the Spheres to plan burns. 

Here is an [implementation of the Lambert Problem](https://github.com/nsarrazin/AstroPynamics) as a reference.

@HugoGranstrom I'm assigning this to you as I think it's a challenge you would enjoy sinking your teeth into, but also because it's beyond my pay grade 🤣 !  I can imagine that you might need some things to be developed to be able to knock this one out of the park, so I encourage you to create an issue with whatever you need to be able to do this. And if it's not to your liking, no worries!

**Comment by HugoGranstrom** [comment]
Now we are talking about some seriously juicy stuff!!! 🚀😄 I have always wondered how they plan their trajectories, and now I have a good reason to study it further 📚 This is really exciting!!! I'll go ahead and try to wrap my head around this the next couple of days and I will aim to hopefully have a somewhat working test version in my Python environment by next weekend (fingers crossed 🤞, knock on wood 🌲 🤣 ). 

So that we are on the same page: given some initial conditions (time1, position1, velocity1) we want to know what series of accelerations that will take us to some boundary condition (time2, position2)?

**Comment by TheHappyKoala** [comment]
Yes, exactly! Spot on. Happy I was able to think of something that would tickle your brains. And as I said earlier, if there's something you need from me, let me know and I'll get to it 🚀 🚀 🚀

**Comment by HugoGranstrom** [comment]
Awesome! 👍😄 Let's get to work! 
Will do 😉 thank you!

**Comment by HugoGranstrom** [comment]
I think I have gotten the main idea for how to do the trajectory planning.  It is "just" to patch together some ellipses (one for every sphere of influence we pass through) 😅 What kind of missions do you plan to have? Is it just our Solar System or are you planning more exotic ones? Is the start position on Earth or is it starting from orbit? Are we only heading to planets or do we want to visit smaller objects like asteroids and moons as well? Planet to Planet (crashing into the target) is rather easy but putting the space craft in orbit is a bit trickier. 😄🚀

**Comment by TheHappyKoala** [comment]
You say crashing things into planets is easy? Great, then we have an important component of the future Harmony of the Spheres Space Warfare in place... The aimbot hack, that is to say :rofl: 

I think it would be awesome if you could visit smaller objects like asteroids and moons. In the case of moons maybe it would be more of a case of first getting the trajectory to say Saturn, and then, once at Saturn, get the trajectory to, say, Titan? As for the starting position, I guess lower Earth orbit would do the trick. Pretty much every mission I've read about launches into a lower Earth orbit and then burns its thrusters to head off to its target... The only exception I can think of would be New Horizons which they lobbed straight at Jupiter (if starting on Earth aint too much of an issue, that would be super cool, though). 

If it's a question of patching ellipses, would it be possible to start anywhere, pretty much? Say on Mars and then get a trajectory to Jupiter? 

As for getting into orbit, maybe that is something that should be handled separately? I'm thinking it would be kind of cool to let the user do that themselves with the help of the relative velocity of the spacecraft and the primary. 

I feel like a kid in a candy store here, just pointing at things I like and saying I want THAT... and THAT...oh THAT looks nice, too :rofl: 

What do you think is feasible as far as features go? 

Can't believe how quickly you got the hang of it, though... I spent the better part of a day looking at the Lambert Prblem while looking rather... :confused: :rofl:

**Comment by HugoGranstrom** [comment]
Haha HotS Warfare sounds awesome 😂 

Pretty much yes, from anywhere to everywhere if we neglect the need for fuel 😂 we will have to do some acceleration in the seams of the ellipses but otherwise it should work out perfectly fine. But for efficiency (and sanity) we would have to construct a tree where the Sun is the top node, the planets and lonely asteroids are the next layer and below that are their moons (and even deeper if needed) so we can determine which body we want to construct the current ellipse around. Low Earth orbit sounds like a good start 😉👍 

I think most of what you proposed are reasonable to add in the near future. 

A trip to Titan is very much like you explained, first we go in a orbit around Earth that aims for Titan, then when we have left the Earths Sphere of Influence we go into a orbit around the Sun until we reach Saturn which we orbit and last when we are near enough to Titan we orbit it.

**Comment by HugoGranstrom** [comment]
I'm thinking that step one is to make a space craft auto pilot that can take us from one planet to another body in the solar system (regardless of the fuel usage😅) and for that we would need to know the position of said body in the future. To get it we could either do a simulation to that time or just use Horizon's Ephermis (which is what I find easiest, both in ease of implementation and in runtime efficiency). 
Step two then would be to start choosing our paths more wisely to conserve fuel. 
And step 3 is a full on war game in space 😂

**Comment by TheHappyKoala** [comment]
I think the ideal way to go about it would be to call Horizons whenever you want to know the future position of a celestial body, no 🤔 ? A nice excuse for me to integrate the HORIZONS API into Harmony of the Spheres, I dare say. 

Hmmm... I love the sound of step 3... I don't know why, but I have the feeling that at some point we will be simulating the attack on Buenos Aires by the bugs that takes place at the beginning of Starship Troopers. It's just seems as if though that is the direction in which the universe is moving as far as Harmony of the Spheres goes...

That's a great, great, and why not throw another great in there (GREAT), idea, to display the orbit the spacecraft is on, and yes, we should be able to draw on the ellipseclass for that!!! Just realised I need to add the longitude of the ascending node as a parameter when you add a mass... But first things first: tonight I'm pushing da exoplanet stuff!!! I could have shoehorned it in there, but I decided to fight my instincts and take a more sane approach and make the state management a bit more modular, which took some time, but yea, stay tuned 🚀 🤣

**Comment by TheHappyKoala** [comment]
Exoplanets have been commited. Initial load is a bit slower the first time you load the app, but the response is cached so it's only the first time. Gonna introduce cachebusting and probably do some cleaning up and probably fix a bug or two, as well, but smokaroo, exoplanets, and there will be more. Loading the tess and corot planets for now. Definitely have to add a circumstellar habitability zone shader.

**Comment by TheHappyKoala** [comment]
LOL, already found a bug, albeit a small one... Having said that, check out TESS L 98-59

**Comment by TheHappyKoala** [comment]
<img width="1113" alt="Screen Shot 2019-07-19 at 15 24 09" src="https://user-images.githubusercontent.com/23419647/61538308-63754b80-aa39-11e9-9487-bf8ae1d98e82.png">

Still needs some work graphics wise, but the shader takes two uniforms, temperature and luminosity, and calculates where liquid water could exist. Naturally atmospheric composition, the presence of a magnetic field and so on also play a role, but I think that's a good start. 

And sorry for shit posting in your issue 🤣

**Comment by HugoGranstrom** [comment]
Looks great :-) think it's a good idea to add more features to the exoplanets so you can compare them better. Because on their own, I wouldn't be able to spot any significant differences (except number of planets)😅. 

Horizon is the way to go then 😉 we better look out so we don't stand face to face with a Frankenstein of a gravity simulator and a Call of Duty zombie game 🤣

Haha, we are spreading out our conversations so no one can follow them in any logical order 🤣 we would need a channel to discuss more general things.

**Comment by TheHappyKoala** [comment]
Yea, totally agree. I'm throwing together a grid that you can superimpose on any system, and for exosystems it will be displayed by default, that will have the semimajor axises of all the major planets drawn out with orbit lines and labels. Might sound costly, but I'm gonna render this grid on a canvas, save it as a texture and then apply it to a geometry in a shader, and that way it won't have any run time cost except for the memory that will be allocated to it. 

Aight, then I'll put up a node server for serving Horizons data (you need to have a proxy do it for you, because of the way Horizons works - it's horribly old school!!!), then. Shouldn't take too long as the client is pretty much there in the other repository. Will you be able to chug along without Horizons while you do the prototyping or should I make it a as soon as the exoplanet crap is done I jump on that priority???? 

Yea, we need to get something like slack or discord... Gonna look into that!!!

**Comment by HugoGranstrom** [comment]
I think it will be easier to input my coordinates manually anyway for the testing so I'm in no hurry 😉 it should just be something we can hook on in the end if I do it right. 

That sounds cool, how will you calculate the orbit lines? It could work for this as well 😄

**Comment by TheHappyKoala** [comment]
If you take a look at the utils file you'll notice that I have a bunch of methods dealing with orbital elements and their conversion to state vectors, and with those methods drawing an ellipse is a walk in the park. Given the semimajor axis, eccentricty, argument of periapsis, inclination and the longitude of the ascending node (the last three are the Euler angles, basically) you can uniquely define any orbit. I'm not going to draw the actual orbits, though, as that may end up looking kind of messy, but their semi-major axises, so the apoapsis + periapsis / 2, which for the solar system planets will only make a difference for Mercury and Mars, the only planets whose orbits are noticeably eccentric (something like 20 and 10 % respectively, if I remember things correctly). 

Would you be fine with me adding those util functions to the H3 class as static methods??? Tired of importing them separately and I find I always use them in conjunction with the H3 class. Ideally I'd like to get rid of the utils file altogether, the physics one, not the tiny one with some general crap methods.

**Comment by HugoGranstrom** [comment]
I see, so you will draw a circle with radius of the semi major axis? 

Go ahead 😉 I haven't started coding yet so nothing on my side will break.

**Comment by TheHappyKoala** [comment]
Nahhhhh... I mean, in the special case where the eccentricity is 0, yea, but otherwise the semimajor axis is always wider than the semiminor axis, which is why an ellipse looks like a circle that some guy that spends too much time in the gym decided to sit on... Take the Oumuamua scenario, zoom out, open the add mass tab and then you can see what I'm talking about.

**Comment by TheHappyKoala** [comment]
<img width="1097" alt="Screen Shot 2019-07-20 at 15 42 15" src="https://user-images.githubusercontent.com/23419647/61579418-08108f80-ab05-11e9-8c4c-f4549533e723.png">

Like so... (in case you're wondering about the habitability zone there, I increased the mass of the sun to 65 solar masses, and using the mass-luminosity relationship you can then calculate the boundaries of the habitability zone, lol.

**Comment by HugoGranstrom** [comment]
🤦‍♀️ I'll have to read more thoroughly 🤣 I'm having guest today so these messages have been a bit crammed 😅

**Comment by HugoGranstrom** [comment]
This week has been mostly filled up with holiday activities so I haven't started coding yet sadly. But now I should be free to work on this for the next week 🛠 My first step will be to manage to create and draw an ellipse between Earth and Mars, and I think we already got everything I need for that. 😄 Then I will proceed with trying to get a spacecraft 🚀 from Earth to Mars (and crash it of course 🤣). For now, I think I will just change it's velocity to the "perfect" velocity for the orbit (rocket equation and acceleration comes later). Have you had a code interface for controlling a spacecraft in mind or should I start tinkering with one? 😃

**Comment by TheHappyKoala** [comment]
No problem whatsoever 😄 !!! We work on this project when we have time and feel like it... It's a labour of love ❤️. Happy you've taken some time to enjoy the summer. 

Sounds like an excellent battle plan. But oh no, that means Mars will be covered in a cloud of impact ejecta... Collisions are better, but I still feel like they need some work. But I'm not going to think about that now as the priority for me right now is exoplanets, and then assisting you in whatever way I can and fixing up some Barnes Hut scenarios and related code. 

What do you mean by code interface? Like a class, or...? What variables go into the whole shebang like attitude control, thrust and so on? 

Hoping to get a new build out there today. Also need to finish a wordpress website for a restaurant app that I've been contracted for, so I have a Sunday of code ahead of me 🤣

**Comment by HugoGranstrom** [comment]
Wise man Darrell is here again (as always rather)😉😁 
 
When I have crashed I'm in no shape to say how the ejecta looks fortunately 😅🤣

Where to put the code basically, and how we will control the spacecraft's thrust 😅 I'm thinking of putting an if-statement in the main loop:
```javascript
if(spacecraftControl) {do spacecraft stuff}
```

**Comment by HugoGranstrom** [comment]
Are people still using Wordpress? I thought these drag and drop websites had taken over completely (Wix and such) 😅

**Comment by TheHappyKoala** [comment]
Hahaha, maybe I ought to start a religion and start addressing people as "my children"... Or maybe not.

Ahhh, get what you mean, I presume we'll use the rocket equation for the thrust part and then some simple interface for attitude control (orienting the spacecraft in a certain direction) to determine in which direction the thrust will be applied. But yes, an if statement like that is definitely how we start out 🤣 .  Just feel a bit embarrassed about having you work in the main loop... It's like having somebody over to your house when you haven't tidied up 🤣  . I'll just have to live with that, and with time the quality of the code there is going to improve, and it has already... It was much worse once upon a time, lol. 

As for WordPress, those website builders are okay if you just want a simple website about your dogs online, but if you want something with custom taxonimies that is optimized for speed, then you quickly run into issues with those website builders. It's also very difficult to get the right feel for your site in terms of custom animations and so on. 

Biggest reason, though, is that I just use WordPress as the CMS, the front-end is made with Gatsby (server rended React), which is a lot safer in terms of not getting hacked and faster, too, and if you manage to get that done with Wix you've probably stolen their source code... Not that I'd want to touch it; it's full of bloat and unnecessary scripts and so on.

**Comment by TheHappyKoala** [comment]
SHIT POST ALERT:

<img width="1048" alt="Screen Shot 2019-07-21 at 12 35 26" src="https://user-images.githubusercontent.com/23419647/61590122-22557680-abb4-11e9-9b80-ec455a8141d0.png">

Thought it would be more interesting to add actual orbits as a reference for the exoplanets... There's Mercury's orbit superimposed on the L-98-59 system! 

Should I add Earth's orbit, too, as a reference, you think? Gonna add text labels for them, as well, so people know what the hell they are looking at.

**Comment by HugoGranstrom** [comment]
That is a super duper mega fantastic idea!!!😉😄

**Comment by HugoGranstrom** [comment]
Step one is a partial success, I have managed to get the right shape of the ellipse to be drawn but the rotations are a bit funky. But that should be fixed when we actually add a spacecraft into the code. 

The main loop isn't too bad, some CTRL-F and you find what you want 😉 Something along those lines sounds good. 

I see, haven't made a website much more complicated than a "My dog" website 🤣 so that's probably why I haven't realized those shortcomings yet.

**Comment by TheHappyKoala** [comment]
What about the rotations is funky??? 

But yea, God bless CTRL-F 🎆 ! I'd love to abstract away, say, the logic for setting the position and focus of the camera, but the thing is that doing so would mean increasing either the number of function calls or loops, and in the worst case, both, but time will tell what happens to the code in the scene module. If you have any suggestions, raise a flag 🎏 🤣 

For the exoplanets, with the exception of TESS, I'm thinking about just having a category that includes systems with four or more planets, so as to weed out the in my humble opinion not so interesting exosystems. A lot of them only have a Hot Jupiter running circles around its host star in a day or two and while that's cool and I have nothing personal against Hot Jupiters, I find that it makes finding the really cool exosystems a bit trickier... One option would be to develop a new range of filtering options for the exo scenarios, but right now that's not a rabbit hole I want to climb into. 

What do you think? So my suggestion would be one category for TESS where all kinds of systems are included - the reason being that TESS is in the news quite often and people might find it interesting to be able to simulate all the systems discovered regardless of how many planets are in them - and then another category called Notable Exosystems which will have systems with 4, maybe 3, or more planets.

**Comment by HugoGranstrom** [comment]
It's not the ellipse code that funky, the problem is that I haven't found a way to calculate the rotations 🤣 

Always is there something that one's not happy about an implementation 😅 isn't there anything like inlining in JavaScript? That could cut off the overhead of function calls.

Agree with you, Hot Jupiters may be hot in temperature but not in interest. Go for the number of planets as the filtering factor for the time being. In the future things like number of planets in the habitable zone and such might be things to factor in to make a scenario Notable.

**Comment by TheHappyKoala** [comment]
Did you give H3.rotate a try??? That's the method I use to get the right orbit and ellipse when I add a body or tilt the vectors of the particles that make up Saturn's rings. 

You can see how it's used [here](https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/master/src/js/Physics/particles/ParticleService.ts). The x axis is the argument of perihelion, the y axis the inclination and the z axis the longitude of the ascending node.

**Comment by TheHappyKoala** [comment]
But cool, then we are agreed regarding the exosystems 🤝

**Comment by HugoGranstrom** [comment]
Having problems calculating the argument of perihelion from what I can calculate 🤔😅 I know a way to calculate it but it involves a fair amount of algebra.

**Comment by TheHappyKoala** [comment]
Hehe, it's not for nothing they call it rocket science 🤣

**Comment by HugoGranstrom** [comment]
🤣🤣🤣😂😂😂😂😂 haha

Amazed this is the first time we say it 🤣😂

**Comment by TheHappyKoala** [comment]
<img width="1313" alt="Screen Shot 2019-07-22 at 17 00 56" src="https://user-images.githubusercontent.com/23419647/61643092-6fb01180-aca2-11e9-8780-d6800f6c7ec0.png">

Finally! Just gonna polish the code a bit, add the credits and wiki buttons back and then we're good to go for the next build. Naturally there's more we can do, like procedural planets based on temperatures, size and so on, but for now I think the above is okay.

**Comment by HugoGranstrom** [comment]
Looks good ;-) Maybe Mercury should consider moving to GJ 143 instead as it is at least partially in the habitable zone.

**Comment by TheHappyKoala** [comment]
LOL. Yea, with brief periods in the "hotty" and cold zones... Oh dear, for Mercury's sake I wish we will one day figure out how to have Mercury retire around GJ 143 so that he doesn't have to get incinerated by the Sun in 7 or so billion years. We could rename GJ 143 "Golden Autumn" and make it a planetary retirement home, where planets can live out there days in a dignified and meaningful manner. 

Are you like me in the sense that even though you won't be around to see it you get kind of sad when you think about, for example, how Earth is pretty much at the end of its ability to support life and that it's best days is behind it, or, how, when running a simulation which goes past the 100 year mark you realise that you won't be around at that point?

**Comment by HugoGranstrom** [comment]
Sounds like a business idea aimed at really big customers 😂😉 

I think my youthful naivety is still largely at play, I haven't really pondered much about those kind of question. When I'm doing a simulation I'm more thinking of it as a game to be honest. These kinds of simulations doesn't really tell me something about my future (unless I end up in space 🤣) so I don't put much real life value in them. It could also be that I know the ins and outs of what errors our simulations has 😂. Although they aren't really that big with RKN12 😄.

**Comment by TheHappyKoala** [comment]
Nah, I think it has more to do with my hobby philosopher tendencies than it does with any youthful naivety on your part 🤣

**Comment by HugoGranstrom** [comment]
🤣 🤣  haha may be true

**Comment by HugoGranstrom** [comment]
I think i have done some kind of progress now, it is at least spitting out numbers and not `nan` anymore 🤣 If I have done it correctly I should be getting the initial velocity needed to do the transfer orbit. I took the implementation from Poliastro (another Python orbital mechanics library) and it wasn't too hard to implement. I haven't yet come up with a way to confirm if they are valid though. I tried drawing the ellipse but it is tilted in a totally different way then it should (x: argument of perihelion, y: inclination, z: longitude of something). I check how it is implemented and it I don't think these 3 angles correspond directly to rotations around the xyz-axis. At least not when converting from state vectors 🤔 

I've also tried to add a space craft to the Inner Solar System Scenario and to give it an initial velocity but to no success 😅🤣 Hopefully a good night's sleep will clear my mind 😴

**Comment by TheHappyKoala** [comment]
You're a champion, Hugo! But yea, do treat yourself to some rest 🤣 

I'm going to follow suit... My head is one big swirl of api calls and if statements 😕 🌪

**Comment by TheHappyKoala** [comment]
And let's look into the vector rotations tomorrow... There could very well be something awry about the way in which I implemented the rotations!

**Comment by HugoGranstrom** [comment]
The most probable thing is that I have made a typo somewhere when porting the code over 😅🤣 so I will double and triple check it tomorrow

**Comment by TheHappyKoala** [comment]
On another note I gotta say your RKN12 integrator truly shines with these exoplanet scenarios... It hones in on the appropriate time step without fail, even though the min - max dt range is quite broad... ❤️ tolError

**Comment by HugoGranstrom** [comment]
Awesome! 🚀 I imagine in the future when we talk to the younglings and we tell them: "When I was young we didn't have RKN12 👴 we had to use lower order methods. Life was hard back then" 😅🤣
That's the beauty of adaptiveness 😄  less timestep engineering and more scenarios created!

**Comment by HugoGranstrom** [comment]
I checked what initial velocities the algorithm was spitting out and I wasn't happy 🤣 the z-component was too big, no wonder the ellipse was tilted as much as it was.

**Comment by TheHappyKoala** [comment]
I dare not even imagine what kind of devices our spawn will run their n-body simulations on... In a way I feel sorry for them, because one of the aspects I enjoy about programming these kinds of simulations is having to work against a set of constraints, and having to challenge yourself to find the optimal way of doing things.

**Comment by TheHappyKoala** [comment]
On the subject of the optimal way of doing things... Man, I'm not gonna get up to any gitigans efter again... I just pushed the nastiest commit of all time. From here on onwards I'm going to work with branches. Will force me to focus on one issue, too, rather than dipping my paws in every cook jar my eyes catches sight of 🤣 .

Got some cleaning to do (layout, code and otherwise 🤣) , but I think the exoplanetary stuff is starting to look pretty good.

**Comment by TheHappyKoala** [comment]
I can relate to what you are gonig through... While it might seem like the most obvious thing ever, getting the right impact point from which the shockwave would radiate after a collision was a ROYAL PAIN IN THE ARSE. It was difficult to figure out for a non-rotating sphere but then add in the fact that pretty much all of the spheres we simulate rotate (some shouldn't, though, or rather, their rotation periods should be equal to the period of their orbits, which is to say they should be tidally locked, but hey, that's just on my mental to do list 🤣 ), but once I got it figured out... Oh, all the air I punched. I write my code with my heart on my sleeve.

**Comment by TheHappyKoala** [comment]
By the way, if you find yourself thinking hms it'd be great to have a config file for this variable, like I did for the default scenario and which exoplanet data to fetch, you can check webpack.common.js, where I create global config variables. Feel free to do the same if need be!

**Comment by HugoGranstrom** [comment]
Agreed! Without a challenge most of the fun disappears. And the euphoria when you finally solve a hard problem is just fantastic!😄 When I've got the spacecraft stuff sorted the entire town will know of it 😅😂

But your gitigans are a part of the HotS-experience 😱🤣 I will do a prophecy: "When we are most in need, a wise old man will show us the way in shape of a gitigan". 🙏

**Comment by HugoGranstrom** [comment]
One problem solved, seems my implementation of the Vector cross product was malfunctioning 🤣 Now we get the same velocity as the Python code I "borrowed" from. I think I might have a clue to the rotations as well, the Keplerian elements may need to do all the angles separately like this:
first turn Omega degrees around the z-axis, then turn the new direction i degrees around the x-axis and so on. So I must find a way to set the rotations one after another. I've tried changing the `this.ellipseCurve.rotation` manually but it complains about that it's read-only. A question on that note: what is the default rotation of a ellipseCurve (what is the rotation vector when it lies flat)?

**Comment by HugoGranstrom** [comment]
If it is `(0,0,0)` we are in a bit of trouble, because you can't rotate the zero-vector 😨

**Comment by HugoGranstrom** [comment]
Or perhaps, with a little bit more thought put into it, it doesn't matter because `ellipseCurve.rotation` isn't a spacial vector, rather a list of angles so we couldn't have used it either way. I have do this rotating of vectors first and then calculate the angles and at last pass these to the `ellipseCurve` constructor.

**Comment by TheHappyKoala** [comment]
Yea, the initial value is 0, and then you basically rotate the curve around its axis. Then you have this method which lets you rotate the crap out of it: 

```
  rotateAroundFocus(axisRotations: VectorType): void {
    this.rotation.x = degreesToRadians(axisRotations.x);
    this.rotation.y = degreesToRadians(axisRotations.y);
    this.rotation.z = degreesToRadians(axisRotations.z);
  }

```

Then when you update the ellipse, you do it like so:

```
      const a = scenario.a;
      const e = scenario.e;
      const w = scenario.w;
      const i = scenario.i;

      const ellipse = getEllipse(a, e);

      const scale = scenario.scale;

      this.ellipseCurve.position.z =
        (this.rotatingReferenceFrame.z - primary.z) * scale;

      this.ellipseCurve.update(
        (this.rotatingReferenceFrame.x - primary.x - ellipse.focus) * scale,
        (this.rotatingReferenceFrame.y - primary.y) * scale,
        ellipse.xRadius * scale,
        ellipse.yRadius * scale,
        0,
        2 * Math.PI,
        false,
        0,
        { x: 0, y: i, z: w }
      );
```

As you can tell x is set to 0, so it's not complete, as it does not take the longitude of the ascending node into account

**Comment by TheHappyKoala** [comment]
When I include the longitude of the ascending node, the ellipse that you see drawn does not correspond to the orbit of the mass that you have added, so something fishy is going on there

**Comment by TheHappyKoala** [comment]
This is how I get the vectors for the mass I'm adding:

```

export function getOrbit(primary, secondary, g) {
  const x = primary.x !== undefined ? primary.x : 0;
  const y = primary.y !== undefined ? primary.y : 0;
  const z = primary.z !== undefined ? primary.z : 0;
  const { vx, vy, vz } = primary;

  const apoapsis = getApoapsis(secondary.a, secondary.e);

  const dParams = getDistanceParams(primary, {
    x: x + apoapsis,
    y: y,
    z: z
  });

  const d = Math.sqrt(dParams.dSquared);

  const vMag = getVMag(g, primary, d, secondary.a);

  const secondaryP = new H3()
    .set({ x: apoapsis, y: 0, z: 0 })
    .rotate({ x: 0, y: 0, z: 1 }, secondary.w)
    .rotate({ x: 0, y: 1, z: 0 }, secondary.i);

  const secondaryV = new H3()
    .set({
      x: -dParams.dy * vMag / d,
      y: dParams.dx * vMag / d,
      z: dParams.dz * vMag / d
    })
    .rotate({ x: 0, y: 0, z: 1 }, secondary.w)
    .rotate({ x: 0, y: 1, z: 0 }, secondary.i);

  return {
    ...secondary,
    x: x + secondaryP.x,
    y: y + secondaryP.y,
    z: z + secondaryP.z,
    vx: vx + secondaryV.x,
    vy: vy + secondaryV.y,
    vz: vz + secondaryV.z
  };
}

```

**Comment by TheHappyKoala** [comment]
Maybe I'm not doing the rotations in the right order???

**Comment by TheHappyKoala** [comment]
Not sure I'm being of much help here 🤣

**Comment by HugoGranstrom** [comment]
As I understand it, we need to first rotate longitude of the node around the z-axis, then do the inclination around the x-axis and last the argument of perihelion around the (but rotate it in the inclined plane, not our xyz coordinate system). But I'm not sure how to pull that off as when we update the `ellipseCurve` we must set all of them simultaneously. 

This should give you a hint of how it works: [rotating gif](https://upload.wikimedia.org/wikipedia/commons/8/85/Euler2a.gif?1461803605967).

**Comment by HugoGranstrom** [comment]
Think I might have found the source of all of this 🕵 You are using Three.js for drawing this, right? They seem to be using another set of Euler angles then we need for drawing our ellipses correctly :/ If that is the limiting factor we are in a bit of trouble 😅 not much to do about it then. But if you are manually doing rotateX, rotateY, rotateZ somewhere we could possibly fix this quite easily. 

These angles have made my head explode today 🤣 💥 sorry for bombarding this thread with my thoughts 😅

**Comment by TheHappyKoala** [comment]
Lol, indeed, we're using three.js! There's nothing about it that can't be configured, though, so what do I need to adjust??? I mean, where does three.js go wrong, well not wrong per se, but in the sense that it doesn't play well with our maths???

**Comment by HugoGranstrom** [comment]
We want to do the rotation in this order: ZXZ but right now it does it XYZ, from what I read somewhere in the docs, using the same axis twice wasn't too easy to do, but hopefully I was in the wrong parts of town, so to speak 😅 So basically: we want to be able to decide in which order to do the rotations (and being able to do it twice around the z-axis, the hard part).

**Comment by TheHappyKoala** [comment]
Oh, three.js let's you do that by simply passing the order you want the rotations to take place:

"order - (optional) a string representing the order that the rotations are applied, defaults to 'XYZ' (must be upper case)."

I'll get to it once this build is up, which should be in a few.... *waiting music*

**Comment by TheHappyKoala** [comment]
Just have to fix the css for the credits section... css is cool but it is so not my cup of tea. Have mad respect for css wranglers

**Comment by HugoGranstrom** [comment]
Much easier than I thought 😅 I must have visited some real nasty neighborhoods 🤣

Css is my Achilles's heel 😅 always when I get inspiration for a web app, the initial HTML and Javascript usually goes fine but then comes the CSS... 🤣 Kudos to people who can do this kind of stuff

**Comment by TheHappyKoala** [comment]
Just pushed a new build... Could you check if it works as [it](https://thehappykoala.github.io/Harmony-of-the-Spheres/) should? Got a weird page load first time I tried, but now it's all good, so just to make sure 🤣

**Comment by TheHappyKoala** [comment]
This system looks quite interesting: https://thehappykoala.github.io/Harmony-of-the-Spheres/#/category/La%20Silla/scenario/HD%2010180

**Comment by HugoGranstrom** [comment]
It runs as smooth as butter 😉 I really like the new exoplanet experience, the shader with the habitable zone and the Earth's and Mercury's orbits really does make it much easier to grasp and it becomes more interesting. Planet G seems like a nice place to stay, a bit of both hot and cold, like Sweden 🤣

**Comment by TheHappyKoala** [comment]
Yaaayyy! Happy to hear it was just that first load, then.

Yea... Otherwise it's just a bunch of dots flying about. To make the experience even more awesome, the next features, exoplanet wise, will be procedural planets where things like temperature and mass determine what they look like, and then perhaps some sort of info box, but that would be for all objects simulated in HOS (Harmony of the Spheres, can't be bothered to type it out any more :rofl: ). 

Next up is the ellipsecurve and then mucking about with the hidden gem that is the Barnes Hut integrator!!!

Lol, yea, the flagposts are actually in 2d, but I render them relative to the camera and billboard them (so that they always face the camera), which makes it seem like they are part of the whole 3D scene. Had me think of one of those 90's golf master pro tour super nintendo games. 

Oh, and I just realised that GitHub let's you load static json files as long as you mask them as html, so I'm going to take advantage of that and basically extract all the scenarios out of HOS, which will considerably reduce the size of the javascript bundle and is also nice because it would let us stop mixing data with the client side, which is nice from a separation of concerns point of view.

**Comment by TheHappyKoala** [comment]
And I just purchased gravitysimulator.org 🤣 

Not changing the name of our baby, nor am I going to host it anywhere but GitHub, but I figured a cool brochure website would be neat.

**Comment by HugoGranstrom** [comment]
Now we are talking! 👌😉 Checked out gravitysimulator.com as well.... We don't have any risk if being confused with it, to say the least 😅 This is probably a good idea when we want to market this, githu pages' urls aren't pretty to say the least 🤔😅 

So HOS is the official abbreviation of Harmony of the Spheres? Time for me to stop using HotS (like RotS for Return of the Sith) 🤣. 

What?! They feel so 2030 😱😉 right out of a scifi game. They weren't to shabby back then. There we have some real constraints! Imagine doing HOS on the SNES 😂😅

**Comment by HugoGranstrom** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/5092565/61991877-b1500c00-b056-11e9-9c06-789ad9eba94d.gif)
Because of the rotations this isn't perfect yet but you can see that it trails a path from the Earth area to the Mars area.

**Comment by TheHappyKoala** [comment]
Hotjiggedydoo!!! What do you use to produce the gifs? Awesome work, and phjew, for a second I thought our brave astronauts would get hit by Oumuamua 🤣

**Comment by TheHappyKoala** [comment]
So that is an actual mass you are shooting to Mars?????

**Comment by HugoGranstrom** [comment]
First best Screen Capture extension for Chrome 😅 (my main browser is Firefox but it has some problems with reloading the code). Haha dangerous life out there 🤣

It's just an ellipse that shows the orbit it would have. All I'm actually calculating is the initial velocity and from that I can get the Keplerian Elements

**Comment by HugoGranstrom** [comment]
So sadly no real spacecrafts yet 🤔

**Comment by TheHappyKoala** [comment]
It's all progress :rofl: Small step for a developer, huge leap for... I'll just stop there :rofl:

**Comment by HugoGranstrom** [comment]
When we land our first spacecraft on the Moon you can have your moment 😉🤣

**Comment by TheHappyKoala** [comment]
Closing this issue; will replace it with another one!
