### ISSUE TITLE
Further Lambert work

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#66]
I'm not sure what remains to be done on the Lambert solver, but as you labelled the current iteration of the Lambert solver an initial version, I'm guessing you still want to do some work on it 🚀

**Comment by HugoGranstrom** [comment]
There are one piece of code I still have to implement but then the base function `planFlight` should be completely done. One of the optional parameters it takes is `g` which is set to the default 39.5 but we should pass the value that the user sets in the physics tab. 

Next up I will start on the multiple burns version.

**Comment by TheHappyKoala** [comment]
Awesome. What do you mean by multiple burns? Like you schedule them... Or? Right now, if I want to go to Jupiter, I set Jupiter to be the target with the Sun as the primary, and once clear of Earth's gravitational field, I do another burn to correct for the perturbations caused by Earth's gravitational field. Then I'll usually do one on approach, as well. Probably not the most rocket sciency way to go about it 🤣 . It's sheer awesomeness, however you look at it.

**Comment by HugoGranstrom** [comment]
That's exactly what I thought 😉

**Comment by HugoGranstrom** [comment]
Or no it's not 😅 my approach is first Earth as primary, then the Sun and last Jupiter

**Comment by HugoGranstrom** [comment]
But that's assuming low Earth orbit. But your's seems to work as well 😉 and on a second thought they work roughly the same way, mine is a bit more Hohmann-like but both should take us were we want. 😄 

The real test is trying to aim for one of Jupiter's moons, cause we have to do one additional burn then.

**Comment by HugoGranstrom** [comment]
Not exactly patched conics, rather a realtime patched conic. The real patched conic approach calculates all ellipses at the start and uses just one burn in the beginning and then you get to your destination, but it is not very accurate, because of pertrubations and such. So instead of doing all calculations in the beginning and assuming we will leave Earth's influence at point A, we simulate and see where it happens and does a burn to account for the pertrubations. 
I'm thinking that we every "frame" check which SoR the spacecraft is in and if it has changed from one frame to another, we run `planFlight` with the new body as the `primary`. Does it make sense?😅

**Comment by TheHappyKoala** [comment]
It sure does! I think we should have one auto pilot option where the switch is done automatically and one where you have to do it yourself. I also thought of this sort of game like challenge mode, where one challenge could be to, for example, attain a Juno spacecraft like orbit around Jupiter - as defined by the orbital elements of the spacecrafts orbit, of course we'd tolerate a certain margin of error - and offer extra points for fewer burns, and then you get a "Juno" badge. 

I'm nuts, I know, but it wouldn't require that much work, and then I could code some share challenge with friends and then they could share it on twitter, facebook or whatever 🤣 🚀

**Comment by HugoGranstrom** [comment]
That would be awesome 😄👍 I like games. But I imagine it would be quite a challenge 😅 

Social media integration is as always welcomed 😉

**Comment by TheHappyKoala** [comment]
And brother SOI is back!

**Comment by TheHappyKoala** [comment]
<img width="1351" alt="Screen Shot 2019-09-02 at 02 14 46" src="https://user-images.githubusercontent.com/23419647/64084061-85940600-cd27-11e9-9339-ee390ce624d6.png">

**Comment by HugoGranstrom** [comment]
👌😊👍😉 neat!

**Comment by TheHappyKoala** [comment]
Arrhhh... Finalmente! The solver now works exactly as it ought to. You can go to the Moon, orbit it for a bit, then go to Mars and then back to Earth. Noticed that travelling to Moons only worked when you started out with the primary at origo and then rotated the other masses accordingly, but after running the scenario for a bit, the primary would no longer be at Origo and the whole thing went shit flap... So... Now, whenever we set a trajectory, we rotate the whole scenario so that the primary is at 0, 0, 0, which is what da solver wants and needs. No need for added velocities or positions. The thing finally works!!! For the solar system scenarios we never noticed since the primary would always be somewhere around origo, so in theory at least, this made the solver a tiny, tiny bit more accurate. Gonna go to Max and celebrate with a veggie burger now 🤣

**Comment by TheHappyKoala** [comment]
What do you think would be a cool first scenario? One from our solar system, or a fictional one? I'm thinking some sort of tatoine setup would be pretty radical, where you treat the barycenter of the binary stars as the primary

**Comment by TheHappyKoala** [comment]
And the stars will be called... Wait for it... Darrell and Hugo!!!

So the planets will be Darrell-Hugo B, Darrell-Hugo C, Darrell-Hugo D, Darrell-Hugo E 🤣

**Comment by TheHappyKoala** [comment]
I need to grow up and get some food now

**Comment by HugoGranstrom** [comment]
Woho! 🚀🚀🚀🚀🚀😊😄😎 Pack your things, we are heading for Venus! 😂

Tatooine would be really cool 😉 but I suspect we might be crashing into the stars 😅 but we don't know that until we have tried 😉
Haha 🤣 Awesome names for two awesome stars 👍🤣

I don't have any cool ideas sadly 😅 but if I get one, I'll tell you immediately 😉😎

**Comment by HugoGranstrom** [comment]
Max's veggie burgers are delicious btw 😋🤣

**Comment by TheHappyKoala** [comment]
You know what... I'm just going to make life easy for myself and make the first one a sun earth moon system scenario... Should be a good start, and will be an excellent excuse to cram the apollo model in there 😄 

But yes, they sure are 🍔 !! 

And thanks for all the work you put into Lambert solver and related code... Truly an epic job; different class.

**Comment by TheHappyKoala** [comment]
I'm thinking about writing an article about our project and the joy of open source; you fine with me referencing you in it? No clue where I'll have it published, but I'm thinking CSS tricks, smashnig magazine or if nobody's interested just get it up on Medium

**Comment by HugoGranstrom** [comment]
Sounds like a good approach 😉👍 it was my pleasure 😊

I think alot of people would appreciate it 😁 it's totally fine with me. Tell me if you would want me to write anything science/integrator related for it 😉

**Comment by TheHappyKoala** [comment]
Oh, that would be much appreciated. I'll get a draft together and include a technical technical section where you can discuss the integrators, lambert solver and so on... Think people are interested in the technical side of it.

Speaking of the technical side, I just ran some solar system scenarios for the first time since applying the fix and it's insane... With the burn after leaving Earth's sphere of influence, on all attempts, I hit the planet I was aiming for, like literally!!! I hit Saturn with a time of flight of 10 years... That's just gob smacking cool... The precision!!!

**Comment by HugoGranstrom** [comment]
😅 sorry for the long wait, has been some late nights and early mornings lately. 

Just hit me up when it's ready 😉👍

**Comment by HugoGranstrom** [comment]
That's amazing 🚀😄💪 have you tried hitting Pluto yet?

**Comment by TheHappyKoala** [comment]
Yea, without a correction, I miss 😭It's damn close, though! It's amazing that we've gotten to this point. Got the auto pilot working, too, and I've chosen to include the trajectory ellipse, although without support for hyperbolic trajectories at this point, but hey, that goes into the issue bucket that I'll update after this build 🤣. 

There's only one issue that I'm fixing - only because I can imagine people would want to be able to reset a scenario if they crash into say Jupiter - and that is adding a reset the scenario being played functionality. 

Today it's on!

**Comment by HugoGranstrom** [comment]
What a bummer! 🥶😱😞 
Great, looking forward to testing the new build 😉👍 that's one of the things that have bothered me a bit, having to refresh the page to reset 🤔😅

**Comment by TheHappyKoala** [comment]
Hahaha... Hms, yea, thing is I've been using the url as the source of truth for which scenario to play, because that way you can create routes for them, and while a hodgepog solution would have been easy enough to fix, I wanted it to be scaleable, so what I did was that when you load a new scenario, it's localState is saved in session storage, and then I use this one liner to take care of the state management necessary for this task:

```
export const resetScenario = () =>
  modifyScenarioProperty(
    ...Object.entries(JSON.parse(sessionStorage.getItem('currentScenario'))).map(
      ([key, value]: [string, any]) => ({
        key,
        value
      })
    ),
    {
      key: 'reset',
      value: true
    }
  );
```

Nice thing is that even particles are reset to their original state, so it's a solution that I'm pleased with. Could of course have made it a bit more readable, but for funz I like writing one liners 🤣 It's like the programming equivalent of spoken word poetry, you know?

**Comment by TheHappyKoala** [comment]
I just luuuuve fluid APIs

**Comment by HugoGranstrom** [comment]
Clever 😉👍

**Comment by TheHappyKoala** [comment]
Wouldn't hold it against you if you never thought this day was coming, but tada, there's a build waiting for your review 🤣 ! 

Don't think we've ever deployed a build with so many fundamental changes. In the future build small deploy often is the way to go, I think. It's been a good overhaul, though... And hey, you mentioned the exoplanet scenarios are a bit difficult to browse since you don't know which is which, but know they're sorted in descending order according to how many planets they have... Still room for improvements, but adds a little bit of sense to an otherwise deep ocean of nonsense 🤣 

Damn, gotta stop screwing around and apply for some jobs now 📓

**Comment by TheHappyKoala** [comment]
I'll deploy the code when you've taken a look at the build 🚀

**Comment by TheHappyKoala** [comment]
Couldn't stop myself... Done ✅

**Comment by HugoGranstrom** [comment]
Wohoho!!!! 🚀🚀🚀 It flies like a rocket through space as it nears Jupiter, and then BOOOM 💥💥💥😂😂😂 

It works wonders 😉👍 The exoplanets are easier to explore now as well. 

Not a lot of issues left now 😄👍

**Comment by TheHappyKoala** [comment]
I was genuinely gob smacked when I saw how the spacecraft would actually hit Jupiter... I'll get back to you in a day or two with a draft for the article 😄

**Comment by HugoGranstrom** [comment]
Great 😄👍

**Comment by TheHappyKoala** [comment]
This is pretty cool: https://thehappykoala.github.io/Harmony-of-the-Spheres/#/category/What-If/scenario/Lunacy!

Put every major Moon in our solar system plus Pluto and Ceres in orbit around Mars and that's the result 🤣

**Comment by HugoGranstrom** [comment]
Haha that's a totally derailed moon party 🤣 but I like the zig-zaggy dance moves some of them pulled off 🕺

**Comment by TheHappyKoala** [comment]
Totally! You wanna get in touch with the Poliastro maintainer, by the way, and let him know of our port? And if so, could you also ask if we could add their logo and a link to their repo in the credits section?

**Comment by TheHappyKoala** [comment]
Need to add a resource section in the credits for all the databases and what not that we use

**Comment by HugoGranstrom** [comment]
I'll get in touch with him 😉👍

**Comment by TheHappyKoala** [comment]
Sweet, and Happy Friday 😄 !

**Comment by HugoGranstrom** [comment]
Happy Friday to you too 😉😊
