### ISSUE TITLE
Implement an integrator with an adaptive time step

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#7]
An integrator with an adaptive time step needs to be implemented. Collisions don't really work with a fixed one as sometimes a mass will travel farther in one time step than the radius (I use a simple radius check for collisions since it doesn't require that much computing power) of the body it is smacking into, and as such the hit won't get registered, which looks kind of shoddy. Employing a time step that is fixed but much lower is not an acceptable solution as it would make things painfully slow for the user, not to mention that the amount of vertices that would have to be rendered for the trails would be cosmically huge and would lead to computers, and probably planet Earth as well, melting.

**Comment by HugoGranstrom** [comment]
Have you had any idea of what kind of implementation you want the integrator to be? I'm thinking about an adaptive Runge Kutta (Dormand–Prince for example) or a simpler integrator (like Verlet) in combination with extrapolation (Richardson).

**Comment by TheHappyKoala** [comment]
The integrator that I've been sniffing around is the Runge–Kutta–Fehlberg method, which I've come to understand has an adaptive time step. Haven't had a chance to look at the Dorman-Prince integrator... Does it offer any advantages over the Fehlberg integrator?

**Comment by HugoGranstrom** [comment]
They are basically the same, the Dorman-Prince may be a bit more accurate and I think it requires one more acceleration calculation. But if we get one of them to work, the other would basically just be some other coefficients. So I think RKF is a good one to start with ;-)

**Comment by TheHappyKoala** [comment]
RKF it is, then! Do I need to add you as a collaborator to assign this issue to you? And is that something you would like?

**Comment by HugoGranstrom** [comment]
I will give it a try ;-) 
What would you say about adding some helper functions to make it easier to work with the vectors? Like a multiply all vectors in a list by a scalar or adding two lists of vectors? 

I'm a newbie when it comes to github functionality sadly, but I think I have to do a bit more work to get the honor to be a collaborator 😅

**Comment by TheHappyKoala** [comment]
That sounds like a good idea, because it would make working with the code more pleasant, and as a general rule, if one finds oneself repeating a pattern more than once, one ought to make it a general purpose function 😄 

I know a bit of git from work, but I've never been the guy with administrators privileges that assigns permissions and stuff to others, so I'm in unchartered territory, as well! 

Not sure I've said it, but should you have any questions you are more than welcome to ping me any time!

**Comment by HugoGranstrom** [comment]
Ideed, is that something you would want to add yourself? This is your baby after all 😅

Same here, I guess the future will tell 😉 

I'll look into this tomorrow and get back to you then, hopefully with good news. 
I appreciate the support immensely :-)

**Comment by HugoGranstrom** [comment]
I have gotten the Runge-Kutta integrator in RKF to work by itself, now the remaining part is the adaptiveness. There are a few parameters that has to be set for it though. How should we calculate the error? Should it be the total sum of all the error distances or the average? What is a sensible error tolerance (what units do we use)? What range of timesteps should we limit the adaptive method within so it doesn't become to small or too big?

**Comment by HugoGranstrom** [comment]
I have gotten it all to work quite well now. I tested it on the "inner solar system" simulation and when Phaethon was near the Sun I experienced that the simulation slowed down a bit which is good, it indicates that the timestep was smaller during the passing which is what the main goal with an adaptive integrator. 

The problem now is that every simulation needs a separate set of parameters (error tolerance, allowed dt range). But that would be easily added just like every scenario now has a unique dt associated with it. Do you have any good idea on how to choose those?

**Comment by TheHappyKoala** [comment]
Damn, that's impressive, Hugo, and awesome, of course 🚀 🚀 🚀 !!! Fixing those parameters should not be a problem. 

First, for every scenario we can add a key value pair that indicates what kind of system is being simulated (solar system, moon, binary asteroids). Then, in the module that processes the scenarios before they are loaded - index.js in the data/scenarios directory - we can just add some default parameters for each of those simulation types and then people should be able to benefit from the power of your fine integrator 🤠 ! 

I would also add controls to the physics tab for all of these parameters, so that if the keen user wants to modify them for whatever purpose, they are free to do so. Do you think that's a good idea, or is that a case of going overboard? 

If you could submit a pull request and an example of how you specified those parameters for the inner solar system scenario, I'll make setting up the defaults and getting this integrator online with the next build. 

Not sure you noticed, but the Verlet integrator is now online :D! It's not too bad, actually, it can, for example, handle the lunar free return trajectory simulation (one of my favourites, not sure why) without issues, something which cannot be said for the Euler integrator 🤣 🤣 🤣 .

**Comment by HugoGranstrom** [comment]
Thank you 😀 that sounds like a great idea. The values I provided in the pull request works great for the inner solar system (and Oumouamoa, sorry for spelling) but it is a bit slow for the larger simulations like the Planet 9 one. Maybe a bigger `max_dt` or a higher `tol` could help there. 

If you could add controls to the physics tab that would be awesome :rocket:. It would allow more fine tuning for the scenarios. For example two scenarios that are equally big but one has a lot of collision, then that one would need a lower tolerance. An option to change the timestep for the fixed methods as well would be awesome. 

Cool, I have another integrator that's reminiscent of the Verlet but more accurate (and resource hungry) which handles larger step sizes really well. Would that be interesting as a next thing to add?

**Comment by TheHappyKoala** [comment]
No, thank you! This is why open source is like the coolest thing to have been thought of after ketchup! 

Since you agree I'm going to go ahead and add controls to the physics tab. First thing I'm going to do, though, is to fix the default values that I mentioned earlier. This is going to be so cool!!! Now that collisions will work reasonably well, with the introduction of the adaptive time step, I'm going to write a crater shader. Also need to work on making the radius of the impact shockwaves and the mechanics behind the debris cloud more realistic. 

But yes, the more integrators, the better! I think it would be really cool for people to be able to compare different integrators and the results they yield, and maybe even digging into the whys of that. It would also be cool to have a symplectic integrator that conserves energy for folks that would like to run long-time simulations of a system and record the results to a gif, for example. 

So please, consider yourself at liberty to introduce more integrators! 

Having said all of that, now I'm gonna play around a bit with your integrator!! :rocket: :rocket: :rocket:

**Comment by TheHappyKoala** [comment]
Woho... I feel like a kid with a shiny new toy playing around with your integrator. Works beautifully, so I'm closing this issue and opening one for the changes I need to make to the scenarios and so on. 

Gonna read through the code tomorrow, hope you won't mind if I have a question or two!

**Comment by HugoGranstrom** [comment]
Open source is KING! 

That sounds awesome, I thought you had amazing visuals already but with all of that as well I'll be glued to my screen all day. 🖥️

Then more integrators are on their way ;-) What a coincidence then that the integrator I thought of is symplectic, which verlet also is. That was the common theme I talked about. This one is called PEFRL (Position Enhanced Forest-Ruth-Like). Speedwise it's like RK4 but with better accuracy so you can take larger timesteps, and the energy is conserved. 

Glad it worked for you as well 😅 have you gotten it to work on a planetary system (lunar free return, maybe?)? I'll be glad to answer your questions as well as I can. The code is a bit messy but hopefully the parts that are important are understandable. :-D

**Comment by TheHappyKoala** [comment]
Just to give you a heads up: the RKF integrator is now in production! 

Right now all scenarios get defaults that are set like so:

```
  integrator: scenario.integrator !== undefined ? scenario.integrator : 'RKF',
  tol:
    scenario.tol !== undefined ? scenario.tol : scenario.dt - scenario.dt * 0.4,
  maxDt:
    scenario.maxDt !== undefined
      ? scenario.maxDt
      : scenario.dt + scenario.dt * 2,
  minDt:
    scenario.minDt !== undefined
      ? scenario.minDt
      : scenario.dt - scenario.dt * 0.999,  
```

RKF is now the default integrator, but for a few scenarios I've specified that the RK4 integrator should be used... These are scenarios that are mostly about the aesthetics, like the one where Earth gives the rings of Saturn a good pummelling.  

This weekend I'm going to enable users to set defaults themselves, so that they can set for example a default integrator, gravitational constant or whatever they might want to configure. The values will then be saved in local storage so that the defaults persist between sessions (it's nice if the defaults are saved when, for example, a user shuts off their computer!).

**Comment by TheHappyKoala** [comment]
I also added a control for the error tolerance which is displayed if the RKF integrator is the one being used 🚀 !

**Comment by TheHappyKoala** [comment]
Let me know if you'd like to see a wider range tolerance, min and max dt values 😄 Just realised I've been quite conservative with the values I've set in the defaults!

**Comment by TheHappyKoala** [comment]
Oh, one more thing... To answer your question regarding whether it works for the moon scenarios; hell yeh! Check out the lunar free return trajectory, for instance, with the RKF, and then you run it with the RK4... Woho! Look at Neil, Buzz and Mike go!

**Comment by TheHappyKoala** [comment]
Lol, and I just realized Apollo 11 returning to Earth gives rise to a debris cloud like the one that was caused by the Chicxulub impactor 🤣 It's been a long day and I need to stop coding

**Comment by HugoGranstrom** [comment]
What a speed difference compared to RK4! :rocket: Saturn + Earth is a really cool simulation (and a really cool idea that you've come up with ;-D), I think it's my favourite that I've tried so far. 
The local saves are really smart!

The default value worked like a charm :-)

Haha 😄 that's true. Maybe the dinosaurs were smarter than we think 😜

**Comment by TheHappyKoala** [comment]
Happy to hear :smile: !

One small thing: could you use camcel instead of snake case for variable and function names? Feel like a complete turd asking after the work you've done, and I should have added a style guide by now, so if anything it's my fault!!! 

Anyhow, HAPPY FRIDAY, HAPPY MARCH and HAPPY SPRING

**Comment by HugoGranstrom** [comment]
Ooops 😅 it's a habit I have from Python, will try to use camelcase in the future, and to remember to remove all my console.log 😂

**Comment by TheHappyKoala** [comment]
Thanks for the PEFRL integrator!!! Spent the evening reading through Batigyns and Brown's latest paper on planet 9, https://arxiv.org/pdf/1902.10103.pdf, and revised the scenario accordingly. It runs on the PEFRL integrator with a time step of FIVE years... Crazy!!! Neptune must be getting dizzy.

**Comment by HugoGranstrom** [comment]
Planet 9 is so cool :-D if you would remove Planet 9 from the scenario, do the outer dwarf planets behave differently? How big would the effect be would you think? It's crazy to think of a potential massive planet that's out there that we haven't been able to spotted yet.

I know! 🤣 PEFRL is amazing at the things it does best. In my own simulation software I have managed to keep most of the planets of the solar system (Jupiter and outwards) in orbit with a timestep of several hundred days. It may not be accurate byt they stay in orbit at least.

**Comment by TheHappyKoala** [comment]
Hell yeh. Wonder what they'll name it if they find it. Hoping that they'll give it a girl's name since, with the exception of Venus, the Solar System is a proper sausage fest right now. Reading their latest paper, provided I understood the gist of it correctly, it seems like Planet Nine has put the detached objects into their current orbits over the course of the solar system's history. 

There's one important caveat, though; these detached objects transition from being detached objects to scattered objects and vice versa because of Planet Nine's influence. Without Planet Nine, all you would see would be their perihelia precessing around the Sun over millions and billions of years, with some of them being stripped by passing stars or galactic tides when they're at their aphelion. 

Now you might ask yourself why we need to invoke Planet Nine to explain the orbits of these objects, since passing stars could very well have raised their perihelia and detached them from the gravitational influence of the gas giants :hankey:, and the reason for why we do is that passing stars don't have a preference for always flying by the same region of the solar system, so without Planet Nine, one would expect to see objects with these orbits in all directions, but we don't; we see them clustered in one particular region of the sky, and if this is not due to observational bias, there has to be a perturber with the characteristics of Planet Nine shepherding these dwarf planets into the orbits we observe. 

So yes,  you would notice an effect, but you would have to spend an awful lot of time in-front of your pc to do so :rofl: . However, the latest estimate is that the mass of Planet Nine is about five Earth masses, so it's not _that _  big! In the simulation, though, if you change the mass of Planet Nine to that of Jupiter, you will soon find out why Planet Nine can't be that massive; the orbits of the detached objects would quickly get scrambled beyond recognition with some of the objects getting ejected and some flung inwards onto centaur like orbits, although with the huge time step you wouldn't be able to simulate the planet crossing orbits of these would be centaurs. 

But yes, :beers: to PEFRL :smile: ! Today I'm going to run a simulation of 67p's orbit backwards in time and see whether it eventually ends up in the kuiper belt or scattered disk where some researchers think it came from :rocket: :earth_americas: :rofl: !

**Comment by HugoGranstrom** [comment]
I see, that is really interesting :-D 🚀 so Planet 9 would shepherd them in the direction of it's perihelion? 

haha I've got time🤣. It's quite amazing that you can test these things for your self at home, with a little bit of time. You would think it would require a super computer but a browser is really the only thing you need 😃. 

I haven't thought of the names of the planets in that way before but now when you mention it, it's obvious. Do you think they will keep the theme of old gods and mythological creatures? I don't know if there are any old gods that shepherds had but if there is, it would probably be a good candidate. Or maybe Diana, the goddess of hunting. The media is always calling it "The hunt for Planet 9" 🤣 .

Your simulation of 67p sounds really exciting ;-) would be interesting to see if you can backtrack it's orbit 😄

**Comment by TheHappyKoala** [comment]
Indeed, that is my understanding! 

And yes, it's absolutely insane how powerful computers and browsers have become. The next version of JavaScript will improve how floats are handled, which will make the browser an even better environment for simulating these kinds of scenarios. 

Diana would be a great name should the planet turn out to be an actual planet. I think there are rules stipulating what planets can be named after, think the allowed names are Roman and Greek gods, the only Greek name in use being Uranus, if I remember things correctly. The one name I would go for, though, if it has to be of a goddess, would be [Kali ](https://en.wikipedia.org/wiki/Kali). I know it doesn't meet the requirements set by the IAU, but it would be cool to recognise other religions, too... Disclaimer, though, I'm a big fan of Hindu philosophy, so I'm biased 🤣 !

Instead of creating a 67p scenario I ended up creating one for the centaurs - asteroids and comets that cross two or more of the giant planets orbits - since they have very unstable orbits, as crossing the orbits of the gas giants means their orbits are heavily perturbed. Running the scenario the first time around I noticed that the orbits did not form a closed ellipse, and I figured it was because they're too eccentric to simulate properly or that maybe the time step was too high, but then I removed the giant planets to see what their orbits would end up looking like without perturbations, and voila, they formed closed ellipses, even with a very high time step 😄 . 

Seriously, you've developed some awesome integrators!  But the cool thing is how you can actually tell how heavily perturbed these bodies are. Same holds true for the Jupiter family of comets, of which 67P is one. I ran a 500 year simulation of a few of them (haven't pushed this scenario online yet), and after 260 years or so Hartley had a close encounter with Jupiter and its Aphelion was raised to about 8 astronomical units; it was about 5 at the start of the simulation! The RKF integrator is great for simulating these scenarios where close encounters and perturbations play a significant part. 

The RKF integrator will be great for simulating spaceflight, too, which I plan on introducing quite soon 🚀 ! 

If being a nerd was cancer I would have terminal cancer, nuff said 🤠 .

**Comment by HugoGranstrom** [comment]
Great! :-) Interesting, what kind of changes with the floats are coming? 

If they can strip Pluto of it's planetary status they could certainly allow a god from a different religion to name a new planet. 

That you can see the difference by removing the planets is fascinating, I wonder what else we would be able to observe with this 😄 I can't wait for some more spaceflight :-D

**Comment by HugoGranstrom** [comment]
I just noticed something when I compared the `tol` with the estimated error in RKF and it seemed like the error was way smaller then the tolerance which was weird because it is supposed to be just below the tolerance. So I dug further and checked what time steps where used and it showed that `dt` was equal to `maxDt` all the time. In other words, it seems like `maxDt` is too small for RKF to be adaptive other than at extreme events. When you chose your formula for calculating `maxDt`, what was your idea behind it? Do you think this is a problem that needs to be tackled?

**Comment by TheHappyKoala** [comment]
Hey Hugo,

Fixed the issue with the adaptive time step! The error is always breathing the tolerance in the neck now, so to say... However, as often happens when you're coding in a zombie like state, I've managed to introduce a bug where collisions don't produce any debris... zzZZzzzZZzzzz

It was an awesome first day at my new job, though, so I'm not gonna moan and groan too much. Hopefully I'll be able to figure out what happened to the debris and fix it tomorrow night. My apologies for the delay in pushing the newest integrators you've developed.

Having said that, happy Tuesday!

**Comment by HugoGranstrom** [comment]
Great to hear that your first day was good, I guess it's programming related ;-P 

No worries, I already have those ;-) That bug sounds interesting... Btw how are particles handled when calculating the gravitational force? I guess they don't exert any gravitational force on each other, is that correct?

**Comment by TheHappyKoala** [comment]
Hahaha... Yes, it's programming related! Unfortunately I don't get to work on this kind of stuff, though... But it's fun, get to solve problems which I really enjoy. 

Figured out the cause of the bug, and was about to fix it when I saw that NASA was tweeting about an exoplanet they had teased out of the data for Kepler's first object of interest so I went bananas, forgot about the fix, created a simulation of the system and tweeted it at them... Of course this meant I committed a lot of GIT sins, but meh. 

Fix for the time step got online, though! Mind taking a look at it to verify it's all good? Unfortunately the fix is only in the build at the moment (git sins I told ya), but if you replace the old way of setting the defaults with the code below you should be able to test it in your local environment with a console.log in the integrator. Seems like the error is just below the tolerance threshold, now! If it's not good, slap me with a trout and I'll take a look at it.

**Comment by TheHappyKoala** [comment]
And damn, sorry for not answering your question, yes, indeed, they don't feel each others gravitational force, but only that of the regular masses... Otherwise running that simulation would probably lead to something unamusing like a blue screen.

**Comment by HugoGranstrom** [comment]
What a dream it would have been to have this as one's work :-D.

Haha I totally understand you, but it's a good thing because you seem to really enjoy it 😉.

From my tests it seems to work as expected now :-) The only problem is that everything disappears if you set a to small tolerance (1e-15) but I suspect it got in with the gitty sins 🚀 

That's good to know :-D if you sometimes in the future would have an simulation involving many lightweight bodies (lots of comets for example) it would probably be a good approach there as well to only let them be affected and not affect the others, unless comet-comet collisions are important of course.

**Comment by TheHappyKoala** [comment]
Don't think those happen too often... But damn, I feel like a puppy that hasn't learnt not to do number 1 or 2 for that matter inside... Shitting all over the place with my gitigans as opposed to shenanigans, lol. The issue is that I haven't configured the slider to take the change in how the defaults are calculated into account... This weekend I'm going to do some serious spring cleaning. In the words of Britney Spears... I need to treat our gravity simulator right!

**Comment by HugoGranstrom** [comment]
Haha, "gitigans" might be my new favorite word 😂 I quite liked the wide range of tolerances otherwise 😅 but it would of course be a bit fiddly to use the slider from 1e-12 to 1e-5 in a sensible way 🤔 

I took a look at the new exoplanet system and wow does it have a small orbit. Wonder how that could have happened 🤔

**Comment by TheHappyKoala** [comment]
Finally! Fixed the issue with the time step control and the collisions work the way they did before with the debris and so on.

**Comment by TheHappyKoala** [comment]
As for "Hot Jupiters", as these kinds of planets are commonly referred to as, we're not quite sure how they end up orbiting their parent stars at such a short distance. As far as we can tell - and by we I'm, of course, referring to researchers with 1000000 more brain capacity than I could ever dream of - Jupiter mass planets should not be able to form so close to their parent stars as gas and volatiles are blown away by stellar winds. Only heavier elements ought to be able to remain in this part of a protoplanetary disk, and from those you get terrestrial planets that stay that way since there's not much in the way of gas or volatiles for them to vacuum up. This is why most scientists think that Earth's water must have been delivered by asteroids and/or comets after the Earth had formed. 

Therefore, it follows that these Hot Jupiters must have gotten as close as they have to their parent stars by migrating inwards from their place of birth, which is likely to be beyond the frost-line, which is where you find all of the gas giants in our solar system. One way in which this migration could come about is if the gas giant spirals inwards because of drag from the protoplanetary disk, or if looses angular momentum through interactions with planetesimals. Another way is the Kozai-Lidow mechanism, where a third body would perturb the gas giant onto an eccentric orbit around its host star, and over time, tidal circularisation would gradually reduce the aphelion of this planet until it had pretty much a circular orbit around its parent star with a semi-major axis equal to its original perihelion. The third body could be another gas giant, or binary star companion, or a sibling that has since become gravitationally unbound from the system through galactic tides and/or interactions with other stars in the stellar nursery. Could, of course be all of the above mechanisms that give rise to Hot Jupiters, or some entirely different mechanism we haven't thought of.

There's a theory of how our stellar system formed, called the Grand Tack, that stipulates that Jupiter did start migrating inwards, perhaps as close as where Mars is today, before the terrestial planets had formed, but that Saturn eventually ended up in a mean motion resonance with Jupiter which caused Jupiter to head back in the opposite direction, ending up where it is today, at roughly 5 au. This would explain why Mars is so tiny; Jupiter swept up most of the material in that region, so there wassn't much left for Mars to form from. It's also estimated that the asteroid belt ought to have contained an Earth's mass of asteroids, but what we see today is only a fraction of the mass of our Moon (yes, even with Ceres there's hardly anything out there!), but if Jupiter dropped by that region of the solar system, that would explain a lot, as it ought to have scattered most of the planetesimals there left and right.

**Comment by TheHappyKoala** [comment]
Bla, bla, bla

**Comment by HugoGranstrom** [comment]
Wow, that's a whole essay nearly 😃 a very interesting essay! A simulation of a early solar system would be an interesting simulation but that would for sure not be manageable in a browser or a home computer for that matter either (even with algorithms that lowers the complexity like Barnes Hut).

**Comment by TheHappyKoala** [comment]
Yea... But you could make some simplifying assumptions... Like I did with this scenario: [When Galaxies Collide](https://thehappykoala.github.io/Harmony-of-the-Spheres/#/scenario/When%20Galaxies%20Collide) 🤠 👽 🤣 

Lame, but I couldn't stop myself :D! 

I feel awfully awkward asking, but is Barnes Huts something you'd be interested in looking into for more particle oriented simulations? 

Tomorrow I'll hopefully be able to make a commit of the first rocket physics module... Not ready for production, but it's got some cool stuff like delta v budgets and attitude control of the spaceship (a model of the SpaxeX BFR Ship!!!). 

How's the exam prep going????

**Comment by HugoGranstrom** [comment]
that's really clever ;-) it looks to my untrained eyes like a galaxy collision. 

I've tried implementing BH before without much success :/ I always get stuck at constructing the tree in a sensible manner. I don't know which kind data structures to use for it either. But we could have a discussion about a implementation first. For example, should it be a drop-in replacement for generateAccelerationVectors? 

Looking forward to playing with those 😉

The prep is going good so far, thanks 😊
