### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#71]
The readme feels a bit outdated, so let's update it with some proper guidelines for contributors and up to date information about the project, the technologies employed and so forth. @HugoGranstrom If there's anything you feel would be good to include, shoot!

**Comment by HugoGranstrom** [comment]
Good idea, and initiative 😄 It can't hurt making it more invite-able for contributers. Up until now they may have looked at the issues and gotten scared of the chaos there 😅🤣

I can write a short summary for each of the integrators so people can understand the differences between them better. Kind of like a pros/cons list.

**Comment by TheHappyKoala** [comment]
That'd be awesome!
