### ISSUE TITLE
Even more spaceflight

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#82]
We're on our way, but there are still things to do... Figure out how to best get future positions of celestial bodies, where promising options include horizons and orbital elements. Then there's the rocket and fuel stuff, and loads of graphical crap that needs to be done (and conversations to be had, lol).

**Comment by TheHappyKoala** [comment]
Yo, @HugoGranstrom 

Wazup?

**Comment by HugoGranstrom** [comment]
Blazing fast! 🚀

I'll fix the orbital elements stuff up next 💫

**Comment by TheHappyKoala** [comment]
🚀 And as mentioned before I'm gonna do some graphics stuff and integrate the horizons api

**Comment by HugoGranstrom** [comment]
But now my schedule say Sleep so I better follow it 😴 Sleep well

**Comment by TheHappyKoala** [comment]
You too... And yea, need to stop here and catch some zzz's

**Comment by TheHappyKoala** [comment]
<img width="440" alt="Screen Shot 2019-08-22 at 22 32 37" src="https://user-images.githubusercontent.com/23419647/63547624-d4be8780-c52c-11e9-857c-4a2cfb9875d9.png">

Look at our new Sun... With the new Apollo command module passing in-front of it... We're levelling up graphics wise 😄

**Comment by HugoGranstrom** [comment]
Wow 😮 that's a sight to behold. Is the "bubble" around the sun the lensflare effect?

**Comment by TheHappyKoala** [comment]
No, I decided against lensflares because they turned out to be quite annoying after a while... But I ended up redoing the Sun... That's just a halo I added on top of the corona... Does it look off?

**Comment by HugoGranstrom** [comment]
Ok, saw you wrote it in the issue now 😅 

The Corona looks amazing! 😉👍 But the outmost layer does look a bit off, I think it's that it just ends sharply into nothingness.

**Comment by TheHappyKoala** [comment]
True... I'll get right to it 🌞

**Comment by TheHappyKoala** [comment]
<img width="771" alt="Screen Shot 2019-08-22 at 23 29 38" src="https://user-images.githubusercontent.com/23419647/63551204-cd02e100-c534-11e9-8d5f-a37fd332a6c7.png">

**Comment by TheHappyKoala** [comment]
What do you think?

**Comment by HugoGranstrom** [comment]
THAT! Is one truly great looking star

**Comment by HugoGranstrom** [comment]
🎶I'm walking on sunshine

**Comment by TheHappyKoala** [comment]
Aight, then I'm committing this 😄

**Comment by TheHappyKoala** [comment]
🤣

**Comment by HugoGranstrom** [comment]
Also like it how you looked at it from behind the Moon 😉 a bit of Star Wars Ep. IV similarities

**Comment by TheHappyKoala** [comment]
Aight, so that's our new star model!

**Comment by TheHappyKoala** [comment]
I'm all about creating those fancy space shots 📸

**Comment by TheHappyKoala** [comment]
And the corona is animated

**Comment by TheHappyKoala** [comment]
So you see flares and stuff, although there's no science behind that, but sometimes I think you're allowed to just create something that bears a resemblance to nature

**Comment by HugoGranstrom** [comment]
Wow, will have to check it out then 😄😮 Most of us who use this won't be Solar scientists so no one will notice it 🙈 If it flares like a Star and sounds like a star (😜) it's probably a star

**Comment by TheHappyKoala** [comment]
<img width="820" alt="Screen Shot 2019-08-22 at 23 41 10" src="https://user-images.githubusercontent.com/23419647/63551809-64b4ff00-c536-11e9-892b-4e9e8066479c.png">

**Comment by TheHappyKoala** [comment]
Sorry, couldn't stop myself 🤣

**Comment by TheHappyKoala** [comment]
But you were right, feels much better without the halo... I'm hereby appointing you to the position of Chief Stellar Designer

**Comment by HugoGranstrom** [comment]
You can start an entire business selling photos from HOS 😉🤣 The possibilities are endless.

Another feather in my hat 🙏🤣 I may be the most medallioned HOS-contributer around. In the future no star will have to feel ashamed anymore, because plastic surgeon Darrell comes to the rescue 😄

**Comment by TheHappyKoala** [comment]
I'm aware we've discussed this in the past, but figured I would check with you before making the changes I have in mind; RKN12 is the integrator of choice for scenarios where precision is key, but for a lot of the scenarios it is arguably overkill. A lot of the scenarios that don't include objects with highly elliptical orbits can arguably be simulated with Verlet without the simulations falling apart, so I'm thinking about making Verlet the default integrator, and then, for scenarios that require it, we choose an appropriate integrator. For spaceflight scenarios I think RKN12 should be the only option, with the others disabled altogether. 

What do you think? Do we need a more powerful default integrator than Verlet? I don't want to compromise accuracy in such a way that it is noticeable to the user, so I'll leave the call to you, since your understanding of their relative merits and which one might be most suitable as the default is way deeper than mine 😄 . If you say PEFRL, RKN64 or whatever, we'll go with that 🚀 🚀 🚀 🚀 🚀

**Comment by HugoGranstrom** [comment]
Agree that RKN12 is quite overkill most of the time. 😉 But Verlet is a bit too low order to be a default in my opinion. I would go for either PEFRL or one of the Nystrom methods. I don't see any significant difference between them in speed so pick any of them and I will be content 😄👍 The pros of choosing one of them as default is that we can if we want to speed up the simulation, increase the timestep with everything going bonkers 🤣 

Now that we have the Horizon nearly ready we should be able to do a benchmark between all of our integrators to get an idea of which one is most suitable for which scenario.

**Comment by TheHappyKoala** [comment]
Got a soft spot for PEFRL since it was one of your first contributions, so let's make it the default for now, and if it doesn't hold up when we benchmark it against HORIZONS, I guess RKN64 might be a good option

**Comment by HugoGranstrom** [comment]
Yeah it was my second (?) one after Verlet I think 😄 it will do a splendid job 😉👍 APPROVED!! ✔️

**Comment by TheHappyKoala** [comment]
I just realised that we can easily cut down the amount of vertices rendered by only drawing a line segment every 3 - 6 iterations (depending on the time step); you can't tell the difference... So I'm gonna implement this optimization and it's one hell of a big one.

**Comment by TheHappyKoala** [comment]
Yaaayyyy 🚀

**Comment by HugoGranstrom** [comment]
That sounds clever 😉👍 should give us a good boost

**Comment by TheHappyKoala** [comment]
Holy macaronies, the 3D rendering consumes 40 - 60% less memory now depending on the scenario 😮 Always knew the graphics part consumed a fair chunk of memory but I never knew how much of it was made up by the trails!!!

**Comment by HugoGranstrom** [comment]
Wow that's massive! Graphics is surprisingly expensive 😱

**Comment by TheHappyKoala** [comment]
<img width="880" alt="Screen Shot 2019-08-23 at 22 10 44" src="https://user-images.githubusercontent.com/23419647/63620917-f08c6100-c5f2-11e9-8831-6cb6bb3137af.png">

I present the new collision ejecta graphics... Slight shader rewrite, some blending and damn, crisp and clear stuff... Just how I like my explosions.

**Comment by TheHappyKoala** [comment]
Well, the reason for why the vertices that make up the trails are so pricey is because I set their positions with the cpu instead of on the gpu, which also means the position data has to be transferred to the gpu where it's rendered every frame. Problem with doing it on the gpu is that working with state on the gpu is notoriously difficult since the only way of doing that is to write information to a texture, which you then have to read before you set your new state. Slowly getting better at thinking in shaders and glsl, but not quite there yet.

**Comment by TheHappyKoala** [comment]
But I've optimized the hell out of the particle system just now. Before I had 20 000 particles that I would use for collisions, but now I have a pool of only 500 (!) where if that quota is exceeded, existing particles are deleted to make way for the new ones. The size of the pool can be set as a scenario property, so the Saturn scenario can still have thousands of them, but for normal crash and bang scenarios where you just want to chuck stuff into Earth or whatever, a pool of 500 should do, with each collision ejecting 100 particles of ejecta

**Comment by TheHappyKoala** [comment]
<img width="1089" alt="Screen Shot 2019-08-23 at 22 35 21" src="https://user-images.githubusercontent.com/23419647/63622217-5cbc9400-c5f6-11e9-8d16-41d87deec340.png">

**Comment by HugoGranstrom** [comment]
Looks phenomenal 📸 the old ones where just 2d sprites? 

That does sound quite complicated 😅 you are doing good work to understand it 😉

**Comment by HugoGranstrom** [comment]
Btw how are particles' positions and velocity's simulated? Are they in scenario.masses?

**Comment by TheHappyKoala** [comment]
Yes, but the new ones are also sprites. It's just that I now know how to dress sprites in color and glow, so to say.

No... I use this module to generate the positions and velocities of the particles: https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/master/src/js/Physics/particles/ParticleService.ts

**Comment by TheHappyKoala** [comment]
Then there's this puppy: https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/master/src/js/Physics/particles/index.js

It's just Euler, because I figured when it comes to the particles, accuracy is not that important, what's important is that their motion is dictated by their initial state and then whatever gravitational fields they find themselves in

**Comment by TheHappyKoala** [comment]
The iterate method takes the scenario masses, time step and g

**Comment by HugoGranstrom** [comment]
You are a sprite-makeup artist in other words? 😉💅💄

Hmmm... Something I noticed when running the Earth vs Saturn's Rings scenario was that it was a bit slow for my impatient brain so I switched to RKN12 but then the particles started acting different than what they did with RK4. But now I see why that was: RKN12 probably used a larger timestep so the Euler integration became quite sloppy. How big of a slowdown do you reckon we would get if we used Verlet instead? (Roughly 2x slower) because then we could do cool things in the future with them as well (make them orbit in shapes or what not). Or am I too eager to get accurate particles to a high price?😅

**Comment by TheHappyKoala** [comment]
Yea... Cuz they're worth it, you know? 

Oh, this system works well with RKN12 when it comes to the collisions (go figure, the particles don't have to do much besides fall back or continue into eternity, haha) but as you have correctly noticed, when used with a central mass that is integrated with RKN12 and a very large number of particles, things get messy wessy quite quickly. But yea, let's do verlet instead. That's one of the reasons I've been obessing optimizations; so that we can increase the fidelity of the physics! 

But yea, I have great things in mind for the particles... Arrhh arhhh arrhhh

**Comment by HugoGranstrom** [comment]
Of course they are 😉 is raising their spirit as well 🤣

👍 I'll fix it tomorrow (later today actually 🤣). Have got stuck with the new orbital elements stuff so this may give me renewed energy for that 😁 I'm really liking your idea of turning slow code into increased accuracy!

You are an neverending well of wisdom when it comes to ideas 🙏😊😉👍 think what you could accomplish with a few more contributors helping out

**Comment by TheHappyKoala** [comment]
Sweet stuff! And don't stress the orbital elements... I'd say let's explore HORIZONS first! If that works out well, there's no reason why we should get half assed positions using orbital elements, since a call to Horizons for one mass wouldn't take more than 5 seconds, and then you have something very accurate to base your trajectory on. 

But first.... zzzZZzzzzZZzzzZZzzz...

**Comment by HugoGranstrom** [comment]
👍😊indeed. 

Agreed! Zzzzzzzzzzzzzzzzz 😴

**Comment by TheHappyKoala** [comment]
What was the name of the plugin for chrome you used for recording gifs??

**Comment by HugoGranstrom** [comment]
Chrome Capture: https://chrome.google.com/webstore/detail/chrome-capture/ggaabchcecdbomdcnbahdfddfikjmphe

**Comment by HugoGranstrom** [comment]
Just realized we can't use Verlet for the particles because we would need the acceleration of them both before and after all the planets' position has been updated

**Comment by TheHappyKoala** [comment]
Ahums... We don't have any other second order methods?

**Comment by TheHappyKoala** [comment]
Another option is to go the way we have with how we integrate the n-body problem; add some choice and use the right integrator for the right job. Big fan of that approach 🤣 . Like, if we want to simulate particles doing something funky under the power of gravity, maybe we don't need 40 000 particles as in the rings of saturn scenario, but can get away with 3 - 5 thousand, in which case we might as well use RK4 or Pefrl, whichever you find more suitable.

**Comment by TheHappyKoala** [comment]
With the RK4 the particles will handle tight corners like they're on rails 🚆 🤣 🎢

**Comment by TheHappyKoala** [comment]
If my opinions were farts, I would have flatulence issues 🤔

**Comment by HugoGranstrom** [comment]
It's our only second order method (at the moment 😉)

**Comment by HugoGranstrom** [comment]
So basically adding all particles to scenario.masses in the integrators?

**Comment by TheHappyKoala** [comment]
Yes, and no. That's what I will do for the Barnes-Hut scenarios, but for rings and collisional ejecta, I don't want to treat the particles as masses in the n-body problem; nobody knows the particles exist, including the particles themselves, but each particle knows about the masses included in the n-body simulation: so if you're looking to simply be able to simulate n-body problems with particles instead of spheres, that is something I'm going to fix shortly and once that's done you'll be able to use any existing integrator with or without barnes hut...

**Comment by TheHappyKoala** [comment]
Dog is moaning, so I better take him out... Back in a bit

**Comment by HugoGranstrom** [comment]
One approach I've used in back in my Python simulation is to have to separate arrays with masses. Massive bodies in one and very light ones in the other (comets and asteroids basically). Then in the integrators, I iterate over both lists as the "receiver" of force BUT I only iterate over the massive bodies when I calculate the acceleration the body experiences. A sketch of it all:

```
massiveBodies: Array<MassType>
lightBodies: Array<MassType | ParticleType>
for currentBody in (massiveBodies + lightBodies):
  for attractor in massiveBodies:
    currentBody.acceleration += (acceleration from attractor) 
```
This is basically what we already do, but we are limited by the fact that we do them separately.
So this is not the same as using particles instead of spheres, just merely moving the particles' into the integrators as well.  

Looking forward to seeing Barnes Hut make a return 😉

**Comment by HugoGranstrom** [comment]
My approach could make the current implementation of Verlet unusable though (if we limit the number of particles. As we are saving the acceleration from the last timestep and once a particle is removed that prior acceleration would be used for another particle which could cause some nifty behaviors. But I think all the other should work fine

**Comment by TheHappyKoala** [comment]
I see your point, and I contemplated implementing this approach before I started thinking about how central scenario.masses is as a data structure to the application as a whole. It's used for setting the camera, determining which masses can be modified, which masses you can add masses to and so on and so on. You could add a flag to the massless bodies represented by particles indicating that they shouldn't be included in those lists, but that would still mean having to iterate over them when the UI is synced with the simulation, which would incur significant penalties in terms of performance.

**Comment by HugoGranstrom** [comment]
Ahh... I didn't mean to literally add them to scenario.masses but to pass them to the integrators as a separate list and once there treat them as one big list. But afterwards their paths split into masses and particles again

**Comment by HugoGranstrom** [comment]
So basically passing scenario.masses and scenario.particles to the integrator

**Comment by TheHappyKoala** [comment]
I guess that's what [...array, ...array] was invented for 🤣

**Comment by TheHappyKoala** [comment]
But then, if you want to run RKN12 with collisions, you're locked into using it for integrating the trajectories of the particles as well, which seems like overkill

**Comment by TheHappyKoala** [comment]
I was thinking more along the lines of treating n-body particle simulations as an altogether separate kind of simulation category

**Comment by TheHappyKoala** [comment]
That would have their own simplified scene module without all the condiments that come with the standard scenarios

**Comment by HugoGranstrom** [comment]
Yeah that's true 🤔 bad idea

That sounds like a good way of doing the particle only stuff 😉

**Comment by HugoGranstrom** [comment]
Let's go back to Verlet. All I would need would be to have the positions of the bodies before and after the timestep has been taken to accomplish it. So maybe taking a copy of scenario.masses passing it to the integrator would probably do it

**Comment by TheHappyKoala** [comment]
Sounhds excellent 😃 If you need to clone data, the easiest way to go about it is to simply run JSON.parse(JSON.stringify(data))

**Comment by HugoGranstrom** [comment]
Great! Is always tricky to know if doing:
```
const newCopy = oldCopy
```
Is a shallow or deep copy. This certainly is a deep one

**Comment by TheHappyKoala** [comment]
I have tremendous respect for how you never complain about having to work with JavaScript. If I had a dime every time some Java or C# dev complained about having to work with JS I'd be rich... Rich I tell you 🤣.

But yea, what I like about that "hack", is that it will work for whatever shape the data you want to clone has. Yes, you can accomplish the same thing by using map in combination with the array and spread operators, but it always entails nested iterations, not to mention having to use hasOwnProperty(property) to make sure you're not grabbing something from the prototype of the object... 🤢 Do love functional programming, just not for deep cloning nested data structures 🤣

**Comment by HugoGranstrom** [comment]
I don't see any reason to complain 😉 Javascript is a nice, forgiving language. Yes, there are nasty parts to it as well (callback hell) but I haven't touched them here, it's you who are doing the heavy lifting here, which I'm very thankful of 😄 But if you on the other hand forced me to code in Java or C#..... Oh my! I would complain constantly. At least Java is boilerplate coding deluxe 🤣 

Yeah, it definitely saves us a lot of programming time 😀 

I think I might have gotten Verlet to work for the particles. I ran it on the Earth vs Saturn's Rings and it didn't go total havock 🤣 I would like your opinion on it, you have been running that scenario much more than me so you know how it should behave. I will upload the pull request in a few minutes.

**Comment by TheHappyKoala** [comment]
Lol, sorry bro, but we had our first ever merge conflict and I resolved it beautifully by making oldMasses local to the block where the simulation is iterated, so a patch is coming right up

**Comment by TheHappyKoala** [comment]
Done! Works beautifully and it's still a silky ride without hickups! Thanks for taking the particle integrator to da next level

**Comment by HugoGranstrom** [comment]
Phew 😌 great to hear!

Everything has a first time 😉

**Comment by TheHappyKoala** [comment]
Hand on your heart, how often do you find yourself using the save scenario functionality...?

**Comment by TheHappyKoala** [comment]
Maybe we should keep it because it's cool just to have the functionality there

**Comment by HugoGranstrom** [comment]
Never 😅 the number of scenarios is low enough that I can find it manually. One use case where I would use it though, is if I found one of the exoplanet scenarios interesting. Those are a pain to remember which one's which 🤣

**Comment by TheHappyKoala** [comment]
Oh, there's a lot of them coming up... All systems discovered with four or more planets, and I've introduced pagination to keep things sane 🤣

**Comment by TheHappyKoala** [comment]
So let's keep the save stuff... Probably good to have when we get around to enabling users to create their own simulations

**Comment by HugoGranstrom** [comment]
Wow, how many are we taking about? 😮 
Then this feature may very well come in handy soon 🤣

**Comment by TheHappyKoala** [comment]
Right now all systems with four or more planets, so about a hundred... Thinking about lowering it to 3 in case we'll have about 250, but below that, you get like... Don't know what to call it, universe boilerplate?

**Comment by TheHappyKoala** [comment]
<img width="1189" alt="Screen Shot 2019-08-25 at 23 16 36" src="https://user-images.githubusercontent.com/23419647/63655928-6d077700-c78e-11e9-9d74-7b8bc9e09157.png">

That's what the pagination looks like

**Comment by HugoGranstrom** [comment]
Holy chimoly! That's a lot of exoplanet goodies 😮😁 "Universe boilerplate" will be the new cool word the cool kids will start go around saying all day 🤣
Pagination does indeed seem sane 👍😄

**Comment by HugoGranstrom** [comment]
Today's first day of school again, so my already low contribution levels will go down even further for some time again 🤣 But as always, I'll continue being your.... Advisor(?) 😅

**Comment by TheHappyKoala** [comment]
I couldn't stop myself... All multiplanetary systems are now a part of our fine Appilid00! 

With the pagination it's actually palatable... Next up would be adding the ability to search for systems, but that will only be when spaceflight, barnes hut etc have been taken care of.

You're a contributor extraordinaire! It's all about quality, not quantity 😉 ! I was offered the job I had a code test for, but they wouldn't provide me with a budget for attending conferences and workshops, so I turned them down. Inevitably, once I accept an offer, I have to turn down the pace at which I make contributions - July and August were insane since I didn't work - but it doesn't really matter... All that matters is that I have fun while I'm at it. 

Hope you had a good start to your school year... Suck it up, all that knowledge, as if though you were a sponge 💃 And yes, advisor! That's it. I'll definitely ask for your point of view... First up I'll probably ask you to santity check the next build... Damn, damn: it'll be a game changer 🤣

**Comment by HugoGranstrom** [comment]
Wow! 😄👍 Now we can be the goto exoplanet explorer.

😊 Your totally right, quality over quantity 😉 

Feels like that should be a standard nowadays 🤔 networking and constantly learning isn't the future, it's today.

👍 Advisor it is then 😄 I'll check it out tonight

**Comment by TheHappyKoala** [comment]
No stress on checking out the build, as it's not quite there yet... Need to fix a bug with the add mass functionality and I want to create some tailored scenarios for the spaceflight - you fine with deploying it with the next build, or is there something you'd like to see done before shipping it (this is your go/no go - your baby 👶 😄 )

**Comment by HugoGranstrom** [comment]
I'm fine with it being included 👍😄🤣

**Comment by TheHappyKoala** [comment]
https://www.youtube.com/watch?v=bYMHAWAK7hk

**Comment by HugoGranstrom** [comment]
I nearly became dizzy by all go/no go 🤣

Have tried it briefly and it looks great 👍😄 the only thing that's a bit inconvinient is browsing through the exoplanets, because they don't seem to come in any sensible order. This will to a large extent be solved by a search functionality though 😉

**Comment by TheHappyKoala** [comment]
Woho... Good news; adding stuff with orbital elements works perfectly now... So, for instance, if you take Mercury's elements and feed them into the gui and click add, the object you added will follow Mercury's orbit. The ellipse used for showing the shape of the orbit of the mass you are about to add works perfectly now, too, so tomorrow I'm going to add it to the space flight scenarios so that you can see the orbit the spacecraft is on. At that point I think we should just call it a build and get our stuff out there 🚀

**Comment by HugoGranstrom** [comment]
That sounds awesome! 😁 What was the fold you had to iron out?

**Comment by TheHappyKoala** [comment]
First I had to get the getOrbit method right, which was easy enough:

 * rotate the z axis by the argument of perihelion
 * rotate the x axis by the inclination
 * rotate the z axis by the longitude of the ascending node

It was the green ellipse that you see when you are adding masses that was tricky to get right, since three.js does not support rotation orders along the lines of "zxz" or "xyx", so when applying the longitude of the ascending node rotation, the current orientation of the ellipse was not taken into account, and whatever value the longitude of the ascending node had would just change the argument of perihelion of the ellipse by the same amount. 

As it turned out, funny given your tweet about hacks, the solution was just to add a dummy wrapper around the ellipse, which meant that first I would rotate the ellipse by argp and i, and then I would rotate the wrapper by o along the z axis, and it worked 🤣 .

**Comment by HugoGranstrom** [comment]
Haha 😂 a tweet with an ounce of truth?!?

That doesn't sound so hacky though 😉 the only thing less hacky would be Three.js adding it on their own

**Comment by TheHappyKoala** [comment]
![chrome-capture](https://user-images.githubusercontent.com/23419647/63957088-0b922180-ca88-11e9-8598-7a962f6ac46d.gif)

Nah, there's no such thing!

**Comment by TheHappyKoala** [comment]
<img width="1079" alt="Screen Shot 2019-08-30 at 18 06 29" src="https://user-images.githubusercontent.com/23419647/64035390-ef0dec00-cb50-11e9-9605-a0a6dfed8175.png">

Man, this shit is so cool I'm about to implode and turn into a Darrell hole from which nothing, not even light, could possibly escape... 

Like now you have your whole freaking trajectory drawn out for you... And it is updated so if you have your butt perturbed, da curve will show... Da curve doesn't lie 🤣 

One question, and I hate asking you now that you're busy with school so if you have stuff to do, I'll just put on my tinkerer hat and get to it, but would it be possible to have state to kepler calculate the elements relative to the primary of the spacecraft? Right now you just feed it with mu, and I guess it assumes that whatever mu is lies at the heart of the coordinate system. 

Mega happy Friday to you, and we pushed another issue thread to 💯 🤣 🚀

**Comment by TheHappyKoala** [comment]
![chrome-capture-min](https://user-images.githubusercontent.com/23419647/64041271-592d8d80-cb5f-11e9-988d-e82f3cd249d5.gif)

**Comment by TheHappyKoala** [comment]
I just hit Venus in the bulls eye. I'm so happy asteroids don't have Lambert solvers 🤣

**Comment by TheHappyKoala** [comment]
Sometimes things don't end well for my astronauts as the trajectory takes them through Earth before they get to their destination 🤣

**Comment by TheHappyKoala** [comment]
<img width="711" alt="Screen Shot 2019-08-30 at 20 57 48" src="https://user-images.githubusercontent.com/23419647/64045158-e7f2d800-cb68-11e9-9d22-6f077772fa03.png">

Neil, Buzz and Mike got lost

**Comment by HugoGranstrom** [comment]
Awesome, awesome, AWESOME! 😁😄👌🚀🚀🚀🚀

I think that was what we had before when it didn't quite work 😅 but I'm not sure, will take a closer look tomorrow

**Comment by TheHappyKoala** [comment]
That was planflight where we commented out these puppies: 

```
  const r1Rel = v1
    .set(r1)
    //.subtract(rCentral)
    .toObject();
  const r2Rel = v1
    .set(r2)
    //.subtract(rCentral)
    .toObject();
```

**Comment by TheHappyKoala** [comment]
I'd say let's save that for the next build, though, and the ellipse. Next build will have rocketry for lack of a better word, incorporated, as well. Managed to figure out how to break down the delta v that the rocket equation gives you into component vectors, so that looks ready to go. 

Thinking of spaceflight in this build as kind of a beta version that demonstrates what is to come, and I'll probably include beta feature in the spaceflight gui to make that clear. Thinking it would be useful to add some sort of help popup explaining the basics of getting from a to b in our solar system and how you need to apply a corrective burn when you move from one sphere of influence to another

**Comment by HugoGranstrom** [comment]
Oh that's right 👍 think we would basically just need to add those to state2kepler and we are done 😉

**Comment by HugoGranstrom** [comment]
And the velocity

**Comment by HugoGranstrom** [comment]
The beta approach sounds wise 👌

**Comment by TheHappyKoala** [comment]
Surprised neither of us explored this possibility, but you can pass a time step that is much higher to the trajectory cruncher than the one the simulation is being run at and it will still give you accurate positions

**Comment by HugoGranstrom** [comment]
Yeah with the low error tolerances we have it shouldn't be any problem raising it a bit for the cruncher

**Comment by TheHappyKoala** [comment]
Man I'm stupid... There's no need to do anything about the stateToKepler method! All that needs fixing is my brain

**Comment by HugoGranstrom** [comment]
Huh?😅

**Comment by TheHappyKoala** [comment]
I just have to subtract the spacecrafts position and velocity vectors from the primary's (say Earth) and then add this.scenario.g * primary.m, and I have me some orbital elements for my spacecraft in whichever sphere of influence it finds itself in

**Comment by HugoGranstrom** [comment]
Yes indeed 😉 but that could be added to state2kepler for ease of use 😉 just passing the primary object as well and doing the subtraction there once instead of everytime we want to use it elsewhere

**Comment by TheHappyKoala** [comment]
True, true... Stop being such a lazy 🐨 , Darrell

**Comment by HugoGranstrom** [comment]
🤣 TheLazyKoala could maybe be a hit.

**Comment by TheHappyKoala** [comment]
<img width="1087" alt="Screen Shot 2019-08-31 at 22 36 05" src="https://user-images.githubusercontent.com/23419647/64068919-c284cd80-cc3f-11e9-91ae-1939fdd941fc.png">

For spaceflight scenarios, I'm automatically updating the rotating reference frame to be the sphere of influence you're in

**Comment by TheHappyKoala** [comment]
Maybe we should add spacecraft orbital elements to the gui... That'd be cool

**Comment by HugoGranstrom** [comment]
Yeah that would be a cool idea 👍😄 those this mean I have to get kepler2State finished?😅

**Comment by TheHappyKoala** [comment]
Hahahahaha... No stress, I was thinking of adding them as stats, not creating inputs for them..  But yea, once we have those, trajectory calculations for plan flight will become a breeeeze, so when you do have time, that'd be 🙇

**Comment by TheHappyKoala** [comment]
Lol, need to generalise the ellipse class to a conic section one

**Comment by HugoGranstrom** [comment]
Ah 😅 that would be cool in the meanwhile 🚀😄😉

**Comment by TheHappyKoala** [comment]
Well, it kind of looks a bit shoddy when the trajectory curve disappears because it's a hyperbolic conic section which is not closed, like when you are leaving Earth for another body... Tried asking if there's a solution provided by three.js, but doesn't seem like it, so hopefully I can cobble something together. Really want that curve there. It's so cooooooooool

**Comment by HugoGranstrom** [comment]
Hope you will find a way to draw it 🤔😉 It doesn't sound too easy if three.js doesn't have it

**Comment by TheHappyKoala** [comment]
I believe a wise man once said... Where there is Darrell, there is also a way 😏 

Jokes aside, you just take the equation for a hyperbola and iteratively plot out the points in the shader, which is also what's done for the ellipse... Now I just need to keep the special case where e = 1 in mind in case somebody manages to conjure up a parabolic orbit 🤣

**Comment by HugoGranstrom** [comment]
That's true though 😉 This is a mission for wise man Darrell 💪

Haha is there much of a difference between a parabola (e=1) and a hyperbola with e = 1.00001?😅

**Comment by TheHappyKoala** [comment]
Shouldn't be, I just gave the equations for conic sections a cursory look on WikiPedia and saw that parabolas are listed as a special case of conic sections, but then again so are circles, and them you can plot without issues with the equation that describes an ellipse

**Comment by HugoGranstrom** [comment]
👍😄 great! So the plan is to skip three.js entirely for the conics?

**Comment by TheHappyKoala** [comment]
Three.js has some pre packaged solutions, but it also allows you to bake your own, so we'll be using three, but with a custom shader... Got it sorted out, and now I'm trying to figure out how to best refactor the ellipseclass into a general conics one without the result being a hodgepodge 🤣

**Comment by HugoGranstrom** [comment]
I see 😊👍

**Comment by TheHappyKoala** [comment]
I'm officially having one of those days... The soi checker aint working, which I'm supreamly confident is due to my work, but it's having me think that writing unit tests for key functionality wouldn't be such a bad idea... Like the state management and key components like the spacecraft controls. 

As always, bear with me 🤣 Closing this issue as it's slowly turning into one of those Russian classics that we're so good at writing.
