### ISSUE TITLE
Migrate this puppy to Gatsby

### ISSUE THREAD

**Issue by TheHappyKoala** [TheHappyKoala/Harmony-of-the-Spheres#99]

**Comment by HugoGranstrom** [comment]
Long time no see 😅 has been feeling weird not to work off HOS last month. Gatsby has been popping up much in my feed lately, what parts of HOS are you thinking of converting to it?

**Comment by TheHappyKoala** [comment]
Good glorious morning :) 

It's not actually that big of a deal; it's still React, the only difference being that the route you land on is rendered on the server, which improves SEO. It's also really, really fast, and will allow us to reduce the JavaScript bundle by a great deal. 

Not a priority, though... First up; Barnes-hut, and then spaceflight mark II! 

How's school treating you? Yea, it's been weird not working on HOS for what I believe is a record two weeks, but I've been quite busy interviewing for jobs and then I fell down the Gatsby hole and only managed to get up after having developed my new website with it.

**Comment by TheHappyKoala** [comment]
(darrellhuffman.me)[https://darrellhuffman.me/]

Realised the project images are png's and clock in at 3-5 megs each, so I need to take care of that 😅 

The about page is probably my favourite

**Comment by HugoGranstrom** [comment]
Ok 👍😄 sounds like an upgrade! 

Mr Barnes Hut is having a good time in front of it 😉👍 my memory is giving up on me, what was the crux with BH?

**Comment by TheHappyKoala** [comment]
There's nothing wrong with BH itself, I just need to write a method that will set the initial conditions properly. When you calculate the initial conditions for a star that is in orbit around a system's center of mass you should only take the mass within its orbit into consideration, and not stuff outside of it, because if you do, your system will accelerate itself apart. Basically I was treating galaxies as Keplerian entities 😅. [Dark matter](https://en.wikipedia.org/wiki/Galaxy_rotation_curve) will have to wait, though.

**Comment by HugoGranstrom** [comment]
Schools going fine, a lot of work but it's manageable. Is there any of the jobs you would be really excited to get? 😄

Haha I really like your website, the About page is a gold nugget 😂👌😎😉

**Comment by TheHappyKoala** [comment]
There's one role that's interesting because it would let me work on projects that are quite close to what I studied at university, although as a developer, but the position is in London and doesn't open up until December (friend works there), so I'll see. The other positions that I interviewed for seemed okay in terms of work, but I always get nervous when one of the main selling points is how important drinking beer after work is to the company culture, which was the case for both of those positions 🤣.

**Comment by TheHappyKoala** [comment]
Closing this one as I'm going to chop this issue up into smaller ones.
